// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TAccessoryItem {

	@TarsStructProperty(order = 0, isRequire = false)
	public int iItemID = 0;
	@TarsStructProperty(order = 1, isRequire = false)
	public int iItemNum = 0;
	@TarsStructProperty(order = 2, isRequire = false)
	public short shItemType = (short)0;

	public int getIItemID() {
		return iItemID;
	}

	public void setIItemID(int iItemID) {
		this.iItemID = iItemID;
	}

	public int getIItemNum() {
		return iItemNum;
	}

	public void setIItemNum(int iItemNum) {
		this.iItemNum = iItemNum;
	}

	public short getShItemType() {
		return shItemType;
	}

	public void setShItemType(short shItemType) {
		this.shItemType = shItemType;
	}

	public TAccessoryItem() {
	}

	public TAccessoryItem(int iItemID, int iItemNum, short shItemType) {
		this.iItemID = iItemID;
		this.iItemNum = iItemNum;
		this.shItemType = shItemType;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(iItemID);
		result = prime * result + TarsUtil.hashCode(iItemNum);
		result = prime * result + TarsUtil.hashCode(shItemType);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TAccessoryItem)) {
			return false;
		}
		TAccessoryItem other = (TAccessoryItem) obj;
		return (
			TarsUtil.equals(iItemID, other.iItemID) &&
			TarsUtil.equals(iItemNum, other.iItemNum) &&
			TarsUtil.equals(shItemType, other.shItemType) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(iItemID, 0);
		_os.write(iItemNum, 1);
		_os.write(shItemType, 2);
	}


	public void readFrom(TarsInputStream _is) {
		this.iItemID = _is.read(iItemID, 0, false);
		this.iItemNum = _is.read(iItemNum, 1, false);
		this.shItemType = _is.read(shItemType, 2, false);
	}

}
