// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TBaseAchiInfo {

	@TarsStructProperty(order = 0, isRequire = false)
	public int iAchiID = 0;
	@TarsStructProperty(order = 1, isRequire = false)
	public int iActivateTime = 0;

	public int getIAchiID() {
		return iAchiID;
	}

	public void setIAchiID(int iAchiID) {
		this.iAchiID = iAchiID;
	}

	public int getIActivateTime() {
		return iActivateTime;
	}

	public void setIActivateTime(int iActivateTime) {
		this.iActivateTime = iActivateTime;
	}

	public TBaseAchiInfo() {
	}

	public TBaseAchiInfo(int iAchiID, int iActivateTime) {
		this.iAchiID = iAchiID;
		this.iActivateTime = iActivateTime;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(iAchiID);
		result = prime * result + TarsUtil.hashCode(iActivateTime);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TBaseAchiInfo)) {
			return false;
		}
		TBaseAchiInfo other = (TBaseAchiInfo) obj;
		return (
			TarsUtil.equals(iAchiID, other.iAchiID) &&
			TarsUtil.equals(iActivateTime, other.iActivateTime) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(iAchiID, 0);
		_os.write(iActivateTime, 1);
	}


	public void readFrom(TarsInputStream _is) {
		this.iAchiID = _is.read(iAchiID, 0, false);
		this.iActivateTime = _is.read(iActivateTime, 1, false);
	}

}
