// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TBuyStatusDb {

	@TarsStructProperty(order = 0, isRequire = false)
	public int iPeriodBuyNum = 0;
	@TarsStructProperty(order = 1, isRequire = false)
	public int iLastBuyTime = 0;

	public int getIPeriodBuyNum() {
		return iPeriodBuyNum;
	}

	public void setIPeriodBuyNum(int iPeriodBuyNum) {
		this.iPeriodBuyNum = iPeriodBuyNum;
	}

	public int getILastBuyTime() {
		return iLastBuyTime;
	}

	public void setILastBuyTime(int iLastBuyTime) {
		this.iLastBuyTime = iLastBuyTime;
	}

	public TBuyStatusDb() {
	}

	public TBuyStatusDb(int iPeriodBuyNum, int iLastBuyTime) {
		this.iPeriodBuyNum = iPeriodBuyNum;
		this.iLastBuyTime = iLastBuyTime;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(iPeriodBuyNum);
		result = prime * result + TarsUtil.hashCode(iLastBuyTime);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TBuyStatusDb)) {
			return false;
		}
		TBuyStatusDb other = (TBuyStatusDb) obj;
		return (
			TarsUtil.equals(iPeriodBuyNum, other.iPeriodBuyNum) &&
			TarsUtil.equals(iLastBuyTime, other.iLastBuyTime) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(iPeriodBuyNum, 0);
		_os.write(iLastBuyTime, 1);
	}


	public void readFrom(TarsInputStream _is) {
		this.iPeriodBuyNum = _is.read(iPeriodBuyNum, 0, false);
		this.iLastBuyTime = _is.read(iLastBuyTime, 1, false);
	}

}
