// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TChargeStatusDb {

	@TarsStructProperty(order = 0, isRequire = false)
	public String sOrderId = "";
	@TarsStructProperty(order = 1, isRequire = false)
	public int iOrderState = 0;
	@TarsStructProperty(order = 2, isRequire = false)
	public int iLastBuyTime = 0;

	public String getSOrderId() {
		return sOrderId;
	}

	public void setSOrderId(String sOrderId) {
		this.sOrderId = sOrderId;
	}

	public int getIOrderState() {
		return iOrderState;
	}

	public void setIOrderState(int iOrderState) {
		this.iOrderState = iOrderState;
	}

	public int getILastBuyTime() {
		return iLastBuyTime;
	}

	public void setILastBuyTime(int iLastBuyTime) {
		this.iLastBuyTime = iLastBuyTime;
	}

	public TChargeStatusDb() {
	}

	public TChargeStatusDb(String sOrderId, int iOrderState, int iLastBuyTime) {
		this.sOrderId = sOrderId;
		this.iOrderState = iOrderState;
		this.iLastBuyTime = iLastBuyTime;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(sOrderId);
		result = prime * result + TarsUtil.hashCode(iOrderState);
		result = prime * result + TarsUtil.hashCode(iLastBuyTime);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TChargeStatusDb)) {
			return false;
		}
		TChargeStatusDb other = (TChargeStatusDb) obj;
		return (
			TarsUtil.equals(sOrderId, other.sOrderId) &&
			TarsUtil.equals(iOrderState, other.iOrderState) &&
			TarsUtil.equals(iLastBuyTime, other.iLastBuyTime) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		if (null != sOrderId) {
			_os.write(sOrderId, 0);
		}
		_os.write(iOrderState, 1);
		_os.write(iLastBuyTime, 2);
	}


	public void readFrom(TarsInputStream _is) {
		this.sOrderId = _is.readString(0, false);
		this.iOrderState = _is.read(iOrderState, 1, false);
		this.iLastBuyTime = _is.read(iLastBuyTime, 2, false);
	}

}
