// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TDBAchiData {

	@TarsStructProperty(order = 1, isRequire = false)
	public int iHonorValue = 0;
	@TarsStructProperty(order = 2, isRequire = false)
	public java.util.List<java.lang.Integer> vHonorGetList = null;
	@TarsStructProperty(order = 4, isRequire = false)
	public java.util.List<TShowAchiInfo> vShowAchi = null;
	@TarsStructProperty(order = 5, isRequire = false)
	public java.util.Map<java.lang.Integer, TOneTypeAchiList> mapAchiList = null;
	@TarsStructProperty(order = 6, isRequire = false)
	public java.util.List<TDBCupInfo> vCupList = null;

	public int getIHonorValue() {
		return iHonorValue;
	}

	public void setIHonorValue(int iHonorValue) {
		this.iHonorValue = iHonorValue;
	}

	public java.util.List<java.lang.Integer> getVHonorGetList() {
		return vHonorGetList;
	}

	public void setVHonorGetList(java.util.List<java.lang.Integer> vHonorGetList) {
		this.vHonorGetList = vHonorGetList;
	}

	public java.util.List<TShowAchiInfo> getVShowAchi() {
		return vShowAchi;
	}

	public void setVShowAchi(java.util.List<TShowAchiInfo> vShowAchi) {
		this.vShowAchi = vShowAchi;
	}

	public java.util.Map<java.lang.Integer, TOneTypeAchiList> getMapAchiList() {
		return mapAchiList;
	}

	public void setMapAchiList(java.util.Map<java.lang.Integer, TOneTypeAchiList> mapAchiList) {
		this.mapAchiList = mapAchiList;
	}

	public java.util.List<TDBCupInfo> getVCupList() {
		return vCupList;
	}

	public void setVCupList(java.util.List<TDBCupInfo> vCupList) {
		this.vCupList = vCupList;
	}

	public TDBAchiData() {
	}

	public TDBAchiData(int iHonorValue, java.util.List<java.lang.Integer> vHonorGetList, java.util.List<TShowAchiInfo> vShowAchi, java.util.Map<java.lang.Integer, TOneTypeAchiList> mapAchiList, java.util.List<TDBCupInfo> vCupList) {
		this.iHonorValue = iHonorValue;
		this.vHonorGetList = vHonorGetList;
		this.vShowAchi = vShowAchi;
		this.mapAchiList = mapAchiList;
		this.vCupList = vCupList;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(iHonorValue);
		result = prime * result + TarsUtil.hashCode(vHonorGetList);
		result = prime * result + TarsUtil.hashCode(vShowAchi);
		result = prime * result + TarsUtil.hashCode(mapAchiList);
		result = prime * result + TarsUtil.hashCode(vCupList);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TDBAchiData)) {
			return false;
		}
		TDBAchiData other = (TDBAchiData) obj;
		return (
			TarsUtil.equals(iHonorValue, other.iHonorValue) &&
			TarsUtil.equals(vHonorGetList, other.vHonorGetList) &&
			TarsUtil.equals(vShowAchi, other.vShowAchi) &&
			TarsUtil.equals(mapAchiList, other.mapAchiList) &&
			TarsUtil.equals(vCupList, other.vCupList) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(iHonorValue, 1);
		if (null != vHonorGetList) {
			_os.write(vHonorGetList, 2);
		}
		if (null != vShowAchi) {
			_os.write(vShowAchi, 4);
		}
		if (null != mapAchiList) {
			_os.write(mapAchiList, 5);
		}
		if (null != vCupList) {
			_os.write(vCupList, 6);
		}
	}

	static java.util.List<java.lang.Integer> cache_vHonorGetList;
	static { 
		cache_vHonorGetList = new java.util.ArrayList<java.lang.Integer>();
		int var_39 = 0;
		cache_vHonorGetList.add(var_39);
	}
	static java.util.List<TShowAchiInfo> cache_vShowAchi;
	static { 
		cache_vShowAchi = new java.util.ArrayList<TShowAchiInfo>();
		TShowAchiInfo var_40 = new TShowAchiInfo();
		cache_vShowAchi.add(var_40);
	}
	static java.util.Map<java.lang.Integer, TOneTypeAchiList> cache_mapAchiList;
	static { 
		cache_mapAchiList = new java.util.HashMap<java.lang.Integer, TOneTypeAchiList>();
		int var_41 = 0;
		TOneTypeAchiList var_42 = new TOneTypeAchiList();
		cache_mapAchiList.put(var_41 ,var_42);
	}
	static java.util.List<TDBCupInfo> cache_vCupList;
	static { 
		cache_vCupList = new java.util.ArrayList<TDBCupInfo>();
		TDBCupInfo var_43 = new TDBCupInfo();
		cache_vCupList.add(var_43);
	}

	public void readFrom(TarsInputStream _is) {
		this.iHonorValue = _is.read(iHonorValue, 1, false);
		this.vHonorGetList = (java.util.List<java.lang.Integer>) _is.read(cache_vHonorGetList, 2, false);
		this.vShowAchi = (java.util.List<TShowAchiInfo>) _is.read(cache_vShowAchi, 4, false);
		this.mapAchiList = (java.util.Map<java.lang.Integer, TOneTypeAchiList>) _is.read(cache_mapAchiList, 5, false);
		this.vCupList = (java.util.List<TDBCupInfo>) _is.read(cache_vCupList, 6, false);
	}

}
