// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TDBBagInfo {

	@TarsStructProperty(order = 0, isRequire = false)
	public java.util.List<TDBBagResource> vecResource = null;
	@TarsStructProperty(order = 1, isRequire = false)
	public java.util.List<TDBBagTimerResource> vecTimerResource = null;
	@TarsStructProperty(order = 2, isRequire = false)
	public TDBStoreData stStoreData = null;
	@TarsStructProperty(order = 3, isRequire = false)
	public TDBBag stBag = null;
	@TarsStructProperty(order = 4, isRequire = false)
	public long uiUniqIDFlag = 0L;

	public java.util.List<TDBBagResource> getVecResource() {
		return vecResource;
	}

	public void setVecResource(java.util.List<TDBBagResource> vecResource) {
		this.vecResource = vecResource;
	}

	public java.util.List<TDBBagTimerResource> getVecTimerResource() {
		return vecTimerResource;
	}

	public void setVecTimerResource(java.util.List<TDBBagTimerResource> vecTimerResource) {
		this.vecTimerResource = vecTimerResource;
	}

	public TDBStoreData getStStoreData() {
		return stStoreData;
	}

	public void setStStoreData(TDBStoreData stStoreData) {
		this.stStoreData = stStoreData;
	}

	public TDBBag getStBag() {
		return stBag;
	}

	public void setStBag(TDBBag stBag) {
		this.stBag = stBag;
	}

	public long getUiUniqIDFlag() {
		return uiUniqIDFlag;
	}

	public void setUiUniqIDFlag(long uiUniqIDFlag) {
		this.uiUniqIDFlag = uiUniqIDFlag;
	}

	public TDBBagInfo() {
	}

	public TDBBagInfo(java.util.List<TDBBagResource> vecResource, java.util.List<TDBBagTimerResource> vecTimerResource, TDBStoreData stStoreData, TDBBag stBag, long uiUniqIDFlag) {
		this.vecResource = vecResource;
		this.vecTimerResource = vecTimerResource;
		this.stStoreData = stStoreData;
		this.stBag = stBag;
		this.uiUniqIDFlag = uiUniqIDFlag;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(vecResource);
		result = prime * result + TarsUtil.hashCode(vecTimerResource);
		result = prime * result + TarsUtil.hashCode(stStoreData);
		result = prime * result + TarsUtil.hashCode(stBag);
		result = prime * result + TarsUtil.hashCode(uiUniqIDFlag);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TDBBagInfo)) {
			return false;
		}
		TDBBagInfo other = (TDBBagInfo) obj;
		return (
			TarsUtil.equals(vecResource, other.vecResource) &&
			TarsUtil.equals(vecTimerResource, other.vecTimerResource) &&
			TarsUtil.equals(stStoreData, other.stStoreData) &&
			TarsUtil.equals(stBag, other.stBag) &&
			TarsUtil.equals(uiUniqIDFlag, other.uiUniqIDFlag) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		if (null != vecResource) {
			_os.write(vecResource, 0);
		}
		if (null != vecTimerResource) {
			_os.write(vecTimerResource, 1);
		}
		if (null != stStoreData) {
			_os.write(stStoreData, 2);
		}
		if (null != stBag) {
			_os.write(stBag, 3);
		}
		_os.write(uiUniqIDFlag, 4);
	}

	static java.util.List<TDBBagResource> cache_vecResource;
	static { 
		cache_vecResource = new java.util.ArrayList<TDBBagResource>();
		TDBBagResource var_23 = new TDBBagResource();
		cache_vecResource.add(var_23);
	}
	static java.util.List<TDBBagTimerResource> cache_vecTimerResource;
	static { 
		cache_vecTimerResource = new java.util.ArrayList<TDBBagTimerResource>();
		TDBBagTimerResource var_24 = new TDBBagTimerResource();
		cache_vecTimerResource.add(var_24);
	}
	static TDBStoreData cache_stStoreData;
	static { 
		cache_stStoreData = new TDBStoreData();
	}
	static TDBBag cache_stBag;
	static { 
		cache_stBag = new TDBBag();
	}

	public void readFrom(TarsInputStream _is) {
		this.vecResource = (java.util.List<TDBBagResource>) _is.read(cache_vecResource, 0, false);
		this.vecTimerResource = (java.util.List<TDBBagTimerResource>) _is.read(cache_vecTimerResource, 1, false);
		this.stStoreData = (TDBStoreData) _is.read(cache_stStoreData, 2, false);
		this.stBag = (TDBBag) _is.read(cache_stBag, 3, false);
		this.uiUniqIDFlag = _is.read(uiUniqIDFlag, 4, false);
	}

}
