// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TDBBag {

	@TarsStructProperty(order = 1, isRequire = false)
	public java.util.List<TDBBagResource> vecSlot = null;

	public java.util.List<TDBBagResource> getVecSlot() {
		return vecSlot;
	}

	public void setVecSlot(java.util.List<TDBBagResource> vecSlot) {
		this.vecSlot = vecSlot;
	}

	public TDBBag() {
	}

	public TDBBag(java.util.List<TDBBagResource> vecSlot) {
		this.vecSlot = vecSlot;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(vecSlot);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TDBBag)) {
			return false;
		}
		TDBBag other = (TDBBag) obj;
		return (
			TarsUtil.equals(vecSlot, other.vecSlot) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		if (null != vecSlot) {
			_os.write(vecSlot, 1);
		}
	}

	static java.util.List<TDBBagResource> cache_vecSlot;
	static { 
		cache_vecSlot = new java.util.ArrayList<TDBBagResource>();
		TDBBagResource var_22 = new TDBBagResource();
		cache_vecSlot.add(var_22);
	}

	public void readFrom(TarsInputStream _is) {
		this.vecSlot = (java.util.List<TDBBagResource>) _is.read(cache_vecSlot, 1, false);
	}

}
