// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TDBCupInfo {

	@TarsStructProperty(order = 0, isRequire = false)
	public short usCupID = (short)0;
	@TarsStructProperty(order = 1, isRequire = false)
	public int iGetTime = 0;

	public short getUsCupID() {
		return usCupID;
	}

	public void setUsCupID(short usCupID) {
		this.usCupID = usCupID;
	}

	public int getIGetTime() {
		return iGetTime;
	}

	public void setIGetTime(int iGetTime) {
		this.iGetTime = iGetTime;
	}

	public TDBCupInfo() {
	}

	public TDBCupInfo(short usCupID, int iGetTime) {
		this.usCupID = usCupID;
		this.iGetTime = iGetTime;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(usCupID);
		result = prime * result + TarsUtil.hashCode(iGetTime);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TDBCupInfo)) {
			return false;
		}
		TDBCupInfo other = (TDBCupInfo) obj;
		return (
			TarsUtil.equals(usCupID, other.usCupID) &&
			TarsUtil.equals(iGetTime, other.iGetTime) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(usCupID, 0);
		_os.write(iGetTime, 1);
	}


	public void readFrom(TarsInputStream _is) {
		this.usCupID = _is.read(usCupID, 0, false);
		this.iGetTime = _is.read(iGetTime, 1, false);
	}

}
