// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TDBStoreData {

	@TarsStructProperty(order = 0, isRequire = false)
	public short usLevel = 1;
	@TarsStructProperty(order = 1, isRequire = false)
	public java.util.List<TDBBagResource> vecResource = null;

	public short getUsLevel() {
		return usLevel;
	}

	public void setUsLevel(short usLevel) {
		this.usLevel = usLevel;
	}

	public java.util.List<TDBBagResource> getVecResource() {
		return vecResource;
	}

	public void setVecResource(java.util.List<TDBBagResource> vecResource) {
		this.vecResource = vecResource;
	}

	public TDBStoreData() {
	}

	public TDBStoreData(short usLevel, java.util.List<TDBBagResource> vecResource) {
		this.usLevel = usLevel;
		this.vecResource = vecResource;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(usLevel);
		result = prime * result + TarsUtil.hashCode(vecResource);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TDBStoreData)) {
			return false;
		}
		TDBStoreData other = (TDBStoreData) obj;
		return (
			TarsUtil.equals(usLevel, other.usLevel) &&
			TarsUtil.equals(vecResource, other.vecResource) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(usLevel, 0);
		if (null != vecResource) {
			_os.write(vecResource, 1);
		}
	}

	static java.util.List<TDBBagResource> cache_vecResource;
	static { 
		cache_vecResource = new java.util.ArrayList<TDBBagResource>();
		TDBBagResource var_21 = new TDBBagResource();
		cache_vecResource.add(var_21);
	}

	public void readFrom(TarsInputStream _is) {
		this.usLevel = _is.read(usLevel, 0, false);
		this.vecResource = (java.util.List<TDBBagResource>) _is.read(cache_vecResource, 1, false);
	}

}
