// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TDBTaskData {

	@TarsStructProperty(order = 0, isRequire = false)
	public java.util.Map<java.lang.Integer, TTaskStatusDb> mapTaskData = null;

	public java.util.Map<java.lang.Integer, TTaskStatusDb> getMapTaskData() {
		return mapTaskData;
	}

	public void setMapTaskData(java.util.Map<java.lang.Integer, TTaskStatusDb> mapTaskData) {
		this.mapTaskData = mapTaskData;
	}

	public TDBTaskData() {
	}

	public TDBTaskData(java.util.Map<java.lang.Integer, TTaskStatusDb> mapTaskData) {
		this.mapTaskData = mapTaskData;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(mapTaskData);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TDBTaskData)) {
			return false;
		}
		TDBTaskData other = (TDBTaskData) obj;
		return (
			TarsUtil.equals(mapTaskData, other.mapTaskData) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		if (null != mapTaskData) {
			_os.write(mapTaskData, 0);
		}
	}

	static java.util.Map<java.lang.Integer, TTaskStatusDb> cache_mapTaskData;
	static { 
		cache_mapTaskData = new java.util.HashMap<java.lang.Integer, TTaskStatusDb>();
		int var_52 = 0;
		TTaskStatusDb var_53 = new TTaskStatusDb();
		cache_mapTaskData.put(var_52 ,var_53);
	}

	public void readFrom(TarsInputStream _is) {
		this.mapTaskData = (java.util.Map<java.lang.Integer, TTaskStatusDb>) _is.read(cache_mapTaskData, 0, false);
	}

}
