// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TEquipmentInfo {

	@TarsStructProperty(order = 0, isRequire = false)
	public java.util.List<java.util.Map<java.lang.Integer, TEquipmentItemDb>> vRoleEquipGrid = null;
	@TarsStructProperty(order = 1, isRequire = false)
	public java.util.Map<java.lang.Integer, java.util.List<TEquipmentItemDb>> mEquipStore = null;
	@TarsStructProperty(order = 2, isRequire = false)
	public java.util.Map<java.lang.Integer, TEquipmentGridDb> mGridDB = null;

	public java.util.List<java.util.Map<java.lang.Integer, TEquipmentItemDb>> getVRoleEquipGrid() {
		return vRoleEquipGrid;
	}

	public void setVRoleEquipGrid(java.util.List<java.util.Map<java.lang.Integer, TEquipmentItemDb>> vRoleEquipGrid) {
		this.vRoleEquipGrid = vRoleEquipGrid;
	}

	public java.util.Map<java.lang.Integer, java.util.List<TEquipmentItemDb>> getMEquipStore() {
		return mEquipStore;
	}

	public void setMEquipStore(java.util.Map<java.lang.Integer, java.util.List<TEquipmentItemDb>> mEquipStore) {
		this.mEquipStore = mEquipStore;
	}

	public java.util.Map<java.lang.Integer, TEquipmentGridDb> getMGridDB() {
		return mGridDB;
	}

	public void setMGridDB(java.util.Map<java.lang.Integer, TEquipmentGridDb> mGridDB) {
		this.mGridDB = mGridDB;
	}

	public TEquipmentInfo() {
	}

	public TEquipmentInfo(java.util.List<java.util.Map<java.lang.Integer, TEquipmentItemDb>> vRoleEquipGrid, java.util.Map<java.lang.Integer, java.util.List<TEquipmentItemDb>> mEquipStore, java.util.Map<java.lang.Integer, TEquipmentGridDb> mGridDB) {
		this.vRoleEquipGrid = vRoleEquipGrid;
		this.mEquipStore = mEquipStore;
		this.mGridDB = mGridDB;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(vRoleEquipGrid);
		result = prime * result + TarsUtil.hashCode(mEquipStore);
		result = prime * result + TarsUtil.hashCode(mGridDB);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TEquipmentInfo)) {
			return false;
		}
		TEquipmentInfo other = (TEquipmentInfo) obj;
		return (
			TarsUtil.equals(vRoleEquipGrid, other.vRoleEquipGrid) &&
			TarsUtil.equals(mEquipStore, other.mEquipStore) &&
			TarsUtil.equals(mGridDB, other.mGridDB) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		if (null != vRoleEquipGrid) {
			_os.write(vRoleEquipGrid, 0);
		}
		if (null != mEquipStore) {
			_os.write(mEquipStore, 1);
		}
		if (null != mGridDB) {
			_os.write(mGridDB, 2);
		}
	}

	static java.util.List<java.util.Map<java.lang.Integer, TEquipmentItemDb>> cache_vRoleEquipGrid;
	static { 
		cache_vRoleEquipGrid = new java.util.ArrayList<java.util.Map<java.lang.Integer, TEquipmentItemDb>>();
		java.util.Map<java.lang.Integer, TEquipmentItemDb> var_25 = new java.util.HashMap<java.lang.Integer, TEquipmentItemDb>();
		int var_26 = 0;
		TEquipmentItemDb var_27 = new TEquipmentItemDb();
		var_25.put(var_26 ,var_27);
		cache_vRoleEquipGrid.add(var_25);
	}
	static java.util.Map<java.lang.Integer, java.util.List<TEquipmentItemDb>> cache_mEquipStore;
	static { 
		cache_mEquipStore = new java.util.HashMap<java.lang.Integer, java.util.List<TEquipmentItemDb>>();
		int var_28 = 0;
		java.util.List<TEquipmentItemDb> var_29 = new java.util.ArrayList<TEquipmentItemDb>();
		TEquipmentItemDb var_30 = new TEquipmentItemDb();
		var_29.add(var_30);
		cache_mEquipStore.put(var_28 ,var_29);
	}
	static java.util.Map<java.lang.Integer, TEquipmentGridDb> cache_mGridDB;
	static { 
		cache_mGridDB = new java.util.HashMap<java.lang.Integer, TEquipmentGridDb>();
		int var_31 = 0;
		TEquipmentGridDb var_32 = new TEquipmentGridDb();
		cache_mGridDB.put(var_31 ,var_32);
	}

	public void readFrom(TarsInputStream _is) {
		this.vRoleEquipGrid = (java.util.List<java.util.Map<java.lang.Integer, TEquipmentItemDb>>) _is.read(cache_vRoleEquipGrid, 0, false);
		this.mEquipStore = (java.util.Map<java.lang.Integer, java.util.List<TEquipmentItemDb>>) _is.read(cache_mEquipStore, 1, false);
		this.mGridDB = (java.util.Map<java.lang.Integer, TEquipmentGridDb>) _is.read(cache_mGridDB, 2, false);
	}

}
