// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TEquipmentGridDb {

	@TarsStructProperty(order = 0, isRequire = false)
	public int iLvl = 0;

	public int getILvl() {
		return iLvl;
	}

	public void setILvl(int iLvl) {
		this.iLvl = iLvl;
	}

	public TEquipmentGridDb() {
	}

	public TEquipmentGridDb(int iLvl) {
		this.iLvl = iLvl;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(iLvl);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TEquipmentGridDb)) {
			return false;
		}
		TEquipmentGridDb other = (TEquipmentGridDb) obj;
		return (
			TarsUtil.equals(iLvl, other.iLvl) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(iLvl, 0);
	}


	public void readFrom(TarsInputStream _is) {
		this.iLvl = _is.read(iLvl, 0, false);
	}

}
