// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class THeiHuZiDb {

	@TarsStructProperty(order = 0, isRequire = false)
	public java.util.List<java.lang.Integer> vecSaleIDList = null;
	@TarsStructProperty(order = 1, isRequire = false)
	public short shFreeUseCnt = (short)0;
	@TarsStructProperty(order = 2, isRequire = false)
	public short shMoneyCnt = (short)0;
	@TarsStructProperty(order = 3, isRequire = false)
	public byte ucAutoFreshCnt = (byte)0;

	public java.util.List<java.lang.Integer> getVecSaleIDList() {
		return vecSaleIDList;
	}

	public void setVecSaleIDList(java.util.List<java.lang.Integer> vecSaleIDList) {
		this.vecSaleIDList = vecSaleIDList;
	}

	public short getShFreeUseCnt() {
		return shFreeUseCnt;
	}

	public void setShFreeUseCnt(short shFreeUseCnt) {
		this.shFreeUseCnt = shFreeUseCnt;
	}

	public short getShMoneyCnt() {
		return shMoneyCnt;
	}

	public void setShMoneyCnt(short shMoneyCnt) {
		this.shMoneyCnt = shMoneyCnt;
	}

	public byte getUcAutoFreshCnt() {
		return ucAutoFreshCnt;
	}

	public void setUcAutoFreshCnt(byte ucAutoFreshCnt) {
		this.ucAutoFreshCnt = ucAutoFreshCnt;
	}

	public THeiHuZiDb() {
	}

	public THeiHuZiDb(java.util.List<java.lang.Integer> vecSaleIDList, short shFreeUseCnt, short shMoneyCnt, byte ucAutoFreshCnt) {
		this.vecSaleIDList = vecSaleIDList;
		this.shFreeUseCnt = shFreeUseCnt;
		this.shMoneyCnt = shMoneyCnt;
		this.ucAutoFreshCnt = ucAutoFreshCnt;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(vecSaleIDList);
		result = prime * result + TarsUtil.hashCode(shFreeUseCnt);
		result = prime * result + TarsUtil.hashCode(shMoneyCnt);
		result = prime * result + TarsUtil.hashCode(ucAutoFreshCnt);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof THeiHuZiDb)) {
			return false;
		}
		THeiHuZiDb other = (THeiHuZiDb) obj;
		return (
			TarsUtil.equals(vecSaleIDList, other.vecSaleIDList) &&
			TarsUtil.equals(shFreeUseCnt, other.shFreeUseCnt) &&
			TarsUtil.equals(shMoneyCnt, other.shMoneyCnt) &&
			TarsUtil.equals(ucAutoFreshCnt, other.ucAutoFreshCnt) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		if (null != vecSaleIDList) {
			_os.write(vecSaleIDList, 0);
		}
		_os.write(shFreeUseCnt, 1);
		_os.write(shMoneyCnt, 2);
		_os.write(ucAutoFreshCnt, 3);
	}

	static java.util.List<java.lang.Integer> cache_vecSaleIDList;
	static { 
		cache_vecSaleIDList = new java.util.ArrayList<java.lang.Integer>();
		int var_50 = 0;
		cache_vecSaleIDList.add(var_50);
	}

	public void readFrom(TarsInputStream _is) {
		this.vecSaleIDList = (java.util.List<java.lang.Integer>) _is.read(cache_vecSaleIDList, 0, false);
		this.shFreeUseCnt = _is.read(shFreeUseCnt, 1, false);
		this.shMoneyCnt = _is.read(shMoneyCnt, 2, false);
		this.ucAutoFreshCnt = _is.read(ucAutoFreshCnt, 3, false);
	}

}
