// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TNpcDBInfo {

	@TarsStructProperty(order = 0, isRequire = false)
	public java.util.List<com.yoooum.tars.yoooum.TBaseNpcInfo> vNPCInfo = null;
	@TarsStructProperty(order = 1, isRequire = false)
	public TTumeimeiDb stTuMeimeiDb = null;
	@TarsStructProperty(order = 2, isRequire = false)
	public TQiaoYiDb stQiaoYiDb = null;
	@TarsStructProperty(order = 3, isRequire = false)
	public THeiHuZiDb stHeiHuZi = null;

	public java.util.List<com.yoooum.tars.yoooum.TBaseNpcInfo> getVNPCInfo() {
		return vNPCInfo;
	}

	public void setVNPCInfo(java.util.List<com.yoooum.tars.yoooum.TBaseNpcInfo> vNPCInfo) {
		this.vNPCInfo = vNPCInfo;
	}

	public TTumeimeiDb getStTuMeimeiDb() {
		return stTuMeimeiDb;
	}

	public void setStTuMeimeiDb(TTumeimeiDb stTuMeimeiDb) {
		this.stTuMeimeiDb = stTuMeimeiDb;
	}

	public TQiaoYiDb getStQiaoYiDb() {
		return stQiaoYiDb;
	}

	public void setStQiaoYiDb(TQiaoYiDb stQiaoYiDb) {
		this.stQiaoYiDb = stQiaoYiDb;
	}

	public THeiHuZiDb getStHeiHuZi() {
		return stHeiHuZi;
	}

	public void setStHeiHuZi(THeiHuZiDb stHeiHuZi) {
		this.stHeiHuZi = stHeiHuZi;
	}

	public TNpcDBInfo() {
	}

	public TNpcDBInfo(java.util.List<com.yoooum.tars.yoooum.TBaseNpcInfo> vNPCInfo, TTumeimeiDb stTuMeimeiDb, TQiaoYiDb stQiaoYiDb, THeiHuZiDb stHeiHuZi) {
		this.vNPCInfo = vNPCInfo;
		this.stTuMeimeiDb = stTuMeimeiDb;
		this.stQiaoYiDb = stQiaoYiDb;
		this.stHeiHuZi = stHeiHuZi;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(vNPCInfo);
		result = prime * result + TarsUtil.hashCode(stTuMeimeiDb);
		result = prime * result + TarsUtil.hashCode(stQiaoYiDb);
		result = prime * result + TarsUtil.hashCode(stHeiHuZi);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TNpcDBInfo)) {
			return false;
		}
		TNpcDBInfo other = (TNpcDBInfo) obj;
		return (
			TarsUtil.equals(vNPCInfo, other.vNPCInfo) &&
			TarsUtil.equals(stTuMeimeiDb, other.stTuMeimeiDb) &&
			TarsUtil.equals(stQiaoYiDb, other.stQiaoYiDb) &&
			TarsUtil.equals(stHeiHuZi, other.stHeiHuZi) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		if (null != vNPCInfo) {
			_os.write(vNPCInfo, 0);
		}
		if (null != stTuMeimeiDb) {
			_os.write(stTuMeimeiDb, 1);
		}
		if (null != stQiaoYiDb) {
			_os.write(stQiaoYiDb, 2);
		}
		if (null != stHeiHuZi) {
			_os.write(stHeiHuZi, 3);
		}
	}

	static java.util.List<com.yoooum.tars.yoooum.TBaseNpcInfo> cache_vNPCInfo;
	static { 
		cache_vNPCInfo = new java.util.ArrayList<com.yoooum.tars.yoooum.TBaseNpcInfo>();
		com.yoooum.tars.yoooum.TBaseNpcInfo var_51 = new com.yoooum.tars.yoooum.TBaseNpcInfo();
		cache_vNPCInfo.add(var_51);
	}
	static TTumeimeiDb cache_stTuMeimeiDb;
	static { 
		cache_stTuMeimeiDb = new TTumeimeiDb();
	}
	static TQiaoYiDb cache_stQiaoYiDb;
	static { 
		cache_stQiaoYiDb = new TQiaoYiDb();
	}
	static THeiHuZiDb cache_stHeiHuZi;
	static { 
		cache_stHeiHuZi = new THeiHuZiDb();
	}

	public void readFrom(TarsInputStream _is) {
		this.vNPCInfo = (java.util.List<com.yoooum.tars.yoooum.TBaseNpcInfo>) _is.read(cache_vNPCInfo, 0, false);
		this.stTuMeimeiDb = (TTumeimeiDb) _is.read(cache_stTuMeimeiDb, 1, false);
		this.stQiaoYiDb = (TQiaoYiDb) _is.read(cache_stQiaoYiDb, 2, false);
		this.stHeiHuZi = (THeiHuZiDb) _is.read(cache_stHeiHuZi, 3, false);
	}

}
