// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TPastureSlotInfo {

	@TarsStructProperty(order = 0, isRequire = false)
	public int iAnimalID = 0;
	@TarsStructProperty(order = 1, isRequire = false)
	public byte cAnimalStatus = (byte)0;
	@TarsStructProperty(order = 2, isRequire = false)
	public long uiNextHungerTime = 0L;
	@TarsStructProperty(order = 3, isRequire = false)
	public long uiNeedGrownSec = 0L;
	@TarsStructProperty(order = 4, isRequire = false)
	public long uiGrazeTime = 0L;

	public int getIAnimalID() {
		return iAnimalID;
	}

	public void setIAnimalID(int iAnimalID) {
		this.iAnimalID = iAnimalID;
	}

	public byte getCAnimalStatus() {
		return cAnimalStatus;
	}

	public void setCAnimalStatus(byte cAnimalStatus) {
		this.cAnimalStatus = cAnimalStatus;
	}

	public long getUiNextHungerTime() {
		return uiNextHungerTime;
	}

	public void setUiNextHungerTime(long uiNextHungerTime) {
		this.uiNextHungerTime = uiNextHungerTime;
	}

	public long getUiNeedGrownSec() {
		return uiNeedGrownSec;
	}

	public void setUiNeedGrownSec(long uiNeedGrownSec) {
		this.uiNeedGrownSec = uiNeedGrownSec;
	}

	public long getUiGrazeTime() {
		return uiGrazeTime;
	}

	public void setUiGrazeTime(long uiGrazeTime) {
		this.uiGrazeTime = uiGrazeTime;
	}

	public TPastureSlotInfo() {
	}

	public TPastureSlotInfo(int iAnimalID, byte cAnimalStatus, long uiNextHungerTime, long uiNeedGrownSec, long uiGrazeTime) {
		this.iAnimalID = iAnimalID;
		this.cAnimalStatus = cAnimalStatus;
		this.uiNextHungerTime = uiNextHungerTime;
		this.uiNeedGrownSec = uiNeedGrownSec;
		this.uiGrazeTime = uiGrazeTime;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(iAnimalID);
		result = prime * result + TarsUtil.hashCode(cAnimalStatus);
		result = prime * result + TarsUtil.hashCode(uiNextHungerTime);
		result = prime * result + TarsUtil.hashCode(uiNeedGrownSec);
		result = prime * result + TarsUtil.hashCode(uiGrazeTime);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TPastureSlotInfo)) {
			return false;
		}
		TPastureSlotInfo other = (TPastureSlotInfo) obj;
		return (
			TarsUtil.equals(iAnimalID, other.iAnimalID) &&
			TarsUtil.equals(cAnimalStatus, other.cAnimalStatus) &&
			TarsUtil.equals(uiNextHungerTime, other.uiNextHungerTime) &&
			TarsUtil.equals(uiNeedGrownSec, other.uiNeedGrownSec) &&
			TarsUtil.equals(uiGrazeTime, other.uiGrazeTime) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(iAnimalID, 0);
		_os.write(cAnimalStatus, 1);
		_os.write(uiNextHungerTime, 2);
		_os.write(uiNeedGrownSec, 3);
		_os.write(uiGrazeTime, 4);
	}


	public void readFrom(TarsInputStream _is) {
		this.iAnimalID = _is.read(iAnimalID, 0, false);
		this.cAnimalStatus = _is.read(cAnimalStatus, 1, false);
		this.uiNextHungerTime = _is.read(uiNextHungerTime, 2, false);
		this.uiNeedGrownSec = _is.read(uiNeedGrownSec, 3, false);
		this.uiGrazeTime = _is.read(uiGrazeTime, 4, false);
	}

}
