// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TPlayerRoleInfo {

	@TarsStructProperty(order = 0, isRequire = false)
	public long uUin = 0L;
	@TarsStructProperty(order = 1, isRequire = false)
	public int iZoneID = 0;
	@TarsStructProperty(order = 2, isRequire = false)
	public String sZoneName = "";
	@TarsStructProperty(order = 3, isRequire = false)
	public long uLastTM = 0L;
	@TarsStructProperty(order = 4, isRequire = false)
	public int iLvl = 0;

	public long getUUin() {
		return uUin;
	}

	public void setUUin(long uUin) {
		this.uUin = uUin;
	}

	public int getIZoneID() {
		return iZoneID;
	}

	public void setIZoneID(int iZoneID) {
		this.iZoneID = iZoneID;
	}

	public String getSZoneName() {
		return sZoneName;
	}

	public void setSZoneName(String sZoneName) {
		this.sZoneName = sZoneName;
	}

	public long getULastTM() {
		return uLastTM;
	}

	public void setULastTM(long uLastTM) {
		this.uLastTM = uLastTM;
	}

	public int getILvl() {
		return iLvl;
	}

	public void setILvl(int iLvl) {
		this.iLvl = iLvl;
	}

	public TPlayerRoleInfo() {
	}

	public TPlayerRoleInfo(long uUin, int iZoneID, String sZoneName, long uLastTM, int iLvl) {
		this.uUin = uUin;
		this.iZoneID = iZoneID;
		this.sZoneName = sZoneName;
		this.uLastTM = uLastTM;
		this.iLvl = iLvl;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(uUin);
		result = prime * result + TarsUtil.hashCode(iZoneID);
		result = prime * result + TarsUtil.hashCode(sZoneName);
		result = prime * result + TarsUtil.hashCode(uLastTM);
		result = prime * result + TarsUtil.hashCode(iLvl);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TPlayerRoleInfo)) {
			return false;
		}
		TPlayerRoleInfo other = (TPlayerRoleInfo) obj;
		return (
			TarsUtil.equals(uUin, other.uUin) &&
			TarsUtil.equals(iZoneID, other.iZoneID) &&
			TarsUtil.equals(sZoneName, other.sZoneName) &&
			TarsUtil.equals(uLastTM, other.uLastTM) &&
			TarsUtil.equals(iLvl, other.iLvl) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(uUin, 0);
		_os.write(iZoneID, 1);
		if (null != sZoneName) {
			_os.write(sZoneName, 2);
		}
		_os.write(uLastTM, 3);
		_os.write(iLvl, 4);
	}


	public void readFrom(TarsInputStream _is) {
		this.uUin = _is.read(uUin, 0, false);
		this.iZoneID = _is.read(iZoneID, 1, false);
		this.sZoneName = _is.readString(2, false);
		this.uLastTM = _is.read(uLastTM, 3, false);
		this.iLvl = _is.read(iLvl, 4, false);
	}

}
