// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TRoleInfo {

	@TarsStructProperty(order = 0, isRequire = false)
	public int iCurRoleID = 0;
	@TarsStructProperty(order = 1, isRequire = false)
	public java.util.List<TRoleDB> vecRoleList = null;

	public int getICurRoleID() {
		return iCurRoleID;
	}

	public void setICurRoleID(int iCurRoleID) {
		this.iCurRoleID = iCurRoleID;
	}

	public java.util.List<TRoleDB> getVecRoleList() {
		return vecRoleList;
	}

	public void setVecRoleList(java.util.List<TRoleDB> vecRoleList) {
		this.vecRoleList = vecRoleList;
	}

	public TRoleInfo() {
	}

	public TRoleInfo(int iCurRoleID, java.util.List<TRoleDB> vecRoleList) {
		this.iCurRoleID = iCurRoleID;
		this.vecRoleList = vecRoleList;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(iCurRoleID);
		result = prime * result + TarsUtil.hashCode(vecRoleList);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TRoleInfo)) {
			return false;
		}
		TRoleInfo other = (TRoleInfo) obj;
		return (
			TarsUtil.equals(iCurRoleID, other.iCurRoleID) &&
			TarsUtil.equals(vecRoleList, other.vecRoleList) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(iCurRoleID, 0);
		if (null != vecRoleList) {
			_os.write(vecRoleList, 1);
		}
	}

	static java.util.List<TRoleDB> cache_vecRoleList;
	static { 
		cache_vecRoleList = new java.util.ArrayList<TRoleDB>();
		TRoleDB var_35 = new TRoleDB();
		cache_vecRoleList.add(var_35);
	}

	public void readFrom(TarsInputStream _is) {
		this.iCurRoleID = _is.read(iCurRoleID, 0, false);
		this.vecRoleList = (java.util.List<TRoleDB>) _is.read(cache_vecRoleList, 1, false);
	}

}
