// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TSoil {

	@TarsStructProperty(order = 0, isRequire = false)
	public byte cStatus = (byte)0;
	@TarsStructProperty(order = 1, isRequire = false)
	public int iPlantID = 0;
	@TarsStructProperty(order = 2, isRequire = false)
	public byte cPlantStatus = (byte)0;
	@TarsStructProperty(order = 3, isRequire = false)
	public long uiNextStageTime = 0L;
	@TarsStructProperty(order = 4, isRequire = false)
	public long uiStartTime = 0L;
	@TarsStructProperty(order = 5, isRequire = false)
	public int iLastGrowSpeed = 0;

	public byte getCStatus() {
		return cStatus;
	}

	public void setCStatus(byte cStatus) {
		this.cStatus = cStatus;
	}

	public int getIPlantID() {
		return iPlantID;
	}

	public void setIPlantID(int iPlantID) {
		this.iPlantID = iPlantID;
	}

	public byte getCPlantStatus() {
		return cPlantStatus;
	}

	public void setCPlantStatus(byte cPlantStatus) {
		this.cPlantStatus = cPlantStatus;
	}

	public long getUiNextStageTime() {
		return uiNextStageTime;
	}

	public void setUiNextStageTime(long uiNextStageTime) {
		this.uiNextStageTime = uiNextStageTime;
	}

	public long getUiStartTime() {
		return uiStartTime;
	}

	public void setUiStartTime(long uiStartTime) {
		this.uiStartTime = uiStartTime;
	}

	public int getILastGrowSpeed() {
		return iLastGrowSpeed;
	}

	public void setILastGrowSpeed(int iLastGrowSpeed) {
		this.iLastGrowSpeed = iLastGrowSpeed;
	}

	public TSoil() {
	}

	public TSoil(byte cStatus, int iPlantID, byte cPlantStatus, long uiNextStageTime, long uiStartTime, int iLastGrowSpeed) {
		this.cStatus = cStatus;
		this.iPlantID = iPlantID;
		this.cPlantStatus = cPlantStatus;
		this.uiNextStageTime = uiNextStageTime;
		this.uiStartTime = uiStartTime;
		this.iLastGrowSpeed = iLastGrowSpeed;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(cStatus);
		result = prime * result + TarsUtil.hashCode(iPlantID);
		result = prime * result + TarsUtil.hashCode(cPlantStatus);
		result = prime * result + TarsUtil.hashCode(uiNextStageTime);
		result = prime * result + TarsUtil.hashCode(uiStartTime);
		result = prime * result + TarsUtil.hashCode(iLastGrowSpeed);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TSoil)) {
			return false;
		}
		TSoil other = (TSoil) obj;
		return (
			TarsUtil.equals(cStatus, other.cStatus) &&
			TarsUtil.equals(iPlantID, other.iPlantID) &&
			TarsUtil.equals(cPlantStatus, other.cPlantStatus) &&
			TarsUtil.equals(uiNextStageTime, other.uiNextStageTime) &&
			TarsUtil.equals(uiStartTime, other.uiStartTime) &&
			TarsUtil.equals(iLastGrowSpeed, other.iLastGrowSpeed) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(cStatus, 0);
		_os.write(iPlantID, 1);
		_os.write(cPlantStatus, 2);
		_os.write(uiNextStageTime, 3);
		_os.write(uiStartTime, 4);
		_os.write(iLastGrowSpeed, 5);
	}


	public void readFrom(TarsInputStream _is) {
		this.cStatus = _is.read(cStatus, 0, false);
		this.iPlantID = _is.read(iPlantID, 1, false);
		this.cPlantStatus = _is.read(cPlantStatus, 2, false);
		this.uiNextStageTime = _is.read(uiNextStageTime, 3, false);
		this.uiStartTime = _is.read(uiStartTime, 4, false);
		this.iLastGrowSpeed = _is.read(iLastGrowSpeed, 5, false);
	}

}
