// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TTaskStatusDb {

	@TarsStructProperty(order = 0, isRequire = true)
	public int iTaskId = 0;
	@TarsStructProperty(order = 1, isRequire = false)
	public long lAcceptTime = 0L;
	@TarsStructProperty(order = 2, isRequire = false)
	public short nTaskState = (short)0;
	@TarsStructProperty(order = 3, isRequire = false)
	public java.util.Map<java.lang.Integer, java.lang.Integer> mapCurTimes = null;
	@TarsStructProperty(order = 4, isRequire = false)
	public int iTargetProcess = 0;

	public int getITaskId() {
		return iTaskId;
	}

	public void setITaskId(int iTaskId) {
		this.iTaskId = iTaskId;
	}

	public long getLAcceptTime() {
		return lAcceptTime;
	}

	public void setLAcceptTime(long lAcceptTime) {
		this.lAcceptTime = lAcceptTime;
	}

	public short getNTaskState() {
		return nTaskState;
	}

	public void setNTaskState(short nTaskState) {
		this.nTaskState = nTaskState;
	}

	public java.util.Map<java.lang.Integer, java.lang.Integer> getMapCurTimes() {
		return mapCurTimes;
	}

	public void setMapCurTimes(java.util.Map<java.lang.Integer, java.lang.Integer> mapCurTimes) {
		this.mapCurTimes = mapCurTimes;
	}

	public int getITargetProcess() {
		return iTargetProcess;
	}

	public void setITargetProcess(int iTargetProcess) {
		this.iTargetProcess = iTargetProcess;
	}

	public TTaskStatusDb() {
	}

	public TTaskStatusDb(int iTaskId, long lAcceptTime, short nTaskState, java.util.Map<java.lang.Integer, java.lang.Integer> mapCurTimes, int iTargetProcess) {
		this.iTaskId = iTaskId;
		this.lAcceptTime = lAcceptTime;
		this.nTaskState = nTaskState;
		this.mapCurTimes = mapCurTimes;
		this.iTargetProcess = iTargetProcess;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(iTaskId);
		result = prime * result + TarsUtil.hashCode(lAcceptTime);
		result = prime * result + TarsUtil.hashCode(nTaskState);
		result = prime * result + TarsUtil.hashCode(mapCurTimes);
		result = prime * result + TarsUtil.hashCode(iTargetProcess);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TTaskStatusDb)) {
			return false;
		}
		TTaskStatusDb other = (TTaskStatusDb) obj;
		return (
			TarsUtil.equals(iTaskId, other.iTaskId) &&
			TarsUtil.equals(lAcceptTime, other.lAcceptTime) &&
			TarsUtil.equals(nTaskState, other.nTaskState) &&
			TarsUtil.equals(mapCurTimes, other.mapCurTimes) &&
			TarsUtil.equals(iTargetProcess, other.iTargetProcess) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(iTaskId, 0);
		_os.write(lAcceptTime, 1);
		_os.write(nTaskState, 2);
		if (null != mapCurTimes) {
			_os.write(mapCurTimes, 3);
		}
		_os.write(iTargetProcess, 4);
	}

	static java.util.Map<java.lang.Integer, java.lang.Integer> cache_mapCurTimes;
	static { 
		cache_mapCurTimes = new java.util.HashMap<java.lang.Integer, java.lang.Integer>();
		int var_44 = 0;
		int var_45 = 0;
		cache_mapCurTimes.put(var_44 ,var_45);
	}

	public void readFrom(TarsInputStream _is) {
		this.iTaskId = _is.read(iTaskId, 0, true);
		this.lAcceptTime = _is.read(lAcceptTime, 1, false);
		this.nTaskState = _is.read(nTaskState, 2, false);
		this.mapCurTimes = (java.util.Map<java.lang.Integer, java.lang.Integer>) _is.read(cache_mapCurTimes, 3, false);
		this.iTargetProcess = _is.read(iTargetProcess, 4, false);
	}

}
