// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TTumeimeiDb {

	@TarsStructProperty(order = 0, isRequire = false)
	public byte Status = 0;
	@TarsStructProperty(order = 1, isRequire = false)
	public java.util.List<com.yoooum.tars.yoooum.TItemInfo> vecDayAward = null;
	@TarsStructProperty(order = 2, isRequire = false)
	public long uLastRefreshTM = 0L;
	@TarsStructProperty(order = 3, isRequire = false)
	public byte AwardStatus = 0;
	@TarsStructProperty(order = 4, isRequire = false)
	public long uTourTM = 0;
	@TarsStructProperty(order = 5, isRequire = false)
	public long uComeBackTM = 0;
	@TarsStructProperty(order = 6, isRequire = false)
	public java.util.List<com.yoooum.tars.yoooum.TItemInfo> vecTourAward = null;
	@TarsStructProperty(order = 7, isRequire = false)
	public int iZoonID = 0;
	@TarsStructProperty(order = 8, isRequire = false)
	public int iEventID = 0;
	@TarsStructProperty(order = 9, isRequire = false)
	public long uZoonEventTM = 0;

	public byte getStatus() {
		return Status;
	}

	public void setStatus(byte Status) {
		this.Status = Status;
	}

	public java.util.List<com.yoooum.tars.yoooum.TItemInfo> getVecDayAward() {
		return vecDayAward;
	}

	public void setVecDayAward(java.util.List<com.yoooum.tars.yoooum.TItemInfo> vecDayAward) {
		this.vecDayAward = vecDayAward;
	}

	public long getULastRefreshTM() {
		return uLastRefreshTM;
	}

	public void setULastRefreshTM(long uLastRefreshTM) {
		this.uLastRefreshTM = uLastRefreshTM;
	}

	public byte getAwardStatus() {
		return AwardStatus;
	}

	public void setAwardStatus(byte AwardStatus) {
		this.AwardStatus = AwardStatus;
	}

	public long getUTourTM() {
		return uTourTM;
	}

	public void setUTourTM(long uTourTM) {
		this.uTourTM = uTourTM;
	}

	public long getUComeBackTM() {
		return uComeBackTM;
	}

	public void setUComeBackTM(long uComeBackTM) {
		this.uComeBackTM = uComeBackTM;
	}

	public java.util.List<com.yoooum.tars.yoooum.TItemInfo> getVecTourAward() {
		return vecTourAward;
	}

	public void setVecTourAward(java.util.List<com.yoooum.tars.yoooum.TItemInfo> vecTourAward) {
		this.vecTourAward = vecTourAward;
	}

	public int getIZoonID() {
		return iZoonID;
	}

	public void setIZoonID(int iZoonID) {
		this.iZoonID = iZoonID;
	}

	public int getIEventID() {
		return iEventID;
	}

	public void setIEventID(int iEventID) {
		this.iEventID = iEventID;
	}

	public long getUZoonEventTM() {
		return uZoonEventTM;
	}

	public void setUZoonEventTM(long uZoonEventTM) {
		this.uZoonEventTM = uZoonEventTM;
	}

	public TTumeimeiDb() {
	}

	public TTumeimeiDb(byte Status, java.util.List<com.yoooum.tars.yoooum.TItemInfo> vecDayAward, long uLastRefreshTM, byte AwardStatus, long uTourTM, long uComeBackTM, java.util.List<com.yoooum.tars.yoooum.TItemInfo> vecTourAward, int iZoonID, int iEventID, long uZoonEventTM) {
		this.Status = Status;
		this.vecDayAward = vecDayAward;
		this.uLastRefreshTM = uLastRefreshTM;
		this.AwardStatus = AwardStatus;
		this.uTourTM = uTourTM;
		this.uComeBackTM = uComeBackTM;
		this.vecTourAward = vecTourAward;
		this.iZoonID = iZoonID;
		this.iEventID = iEventID;
		this.uZoonEventTM = uZoonEventTM;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(Status);
		result = prime * result + TarsUtil.hashCode(vecDayAward);
		result = prime * result + TarsUtil.hashCode(uLastRefreshTM);
		result = prime * result + TarsUtil.hashCode(AwardStatus);
		result = prime * result + TarsUtil.hashCode(uTourTM);
		result = prime * result + TarsUtil.hashCode(uComeBackTM);
		result = prime * result + TarsUtil.hashCode(vecTourAward);
		result = prime * result + TarsUtil.hashCode(iZoonID);
		result = prime * result + TarsUtil.hashCode(iEventID);
		result = prime * result + TarsUtil.hashCode(uZoonEventTM);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TTumeimeiDb)) {
			return false;
		}
		TTumeimeiDb other = (TTumeimeiDb) obj;
		return (
			TarsUtil.equals(Status, other.Status) &&
			TarsUtil.equals(vecDayAward, other.vecDayAward) &&
			TarsUtil.equals(uLastRefreshTM, other.uLastRefreshTM) &&
			TarsUtil.equals(AwardStatus, other.AwardStatus) &&
			TarsUtil.equals(uTourTM, other.uTourTM) &&
			TarsUtil.equals(uComeBackTM, other.uComeBackTM) &&
			TarsUtil.equals(vecTourAward, other.vecTourAward) &&
			TarsUtil.equals(iZoonID, other.iZoonID) &&
			TarsUtil.equals(iEventID, other.iEventID) &&
			TarsUtil.equals(uZoonEventTM, other.uZoonEventTM) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(Status, 0);
		if (null != vecDayAward) {
			_os.write(vecDayAward, 1);
		}
		_os.write(uLastRefreshTM, 2);
		_os.write(AwardStatus, 3);
		_os.write(uTourTM, 4);
		_os.write(uComeBackTM, 5);
		if (null != vecTourAward) {
			_os.write(vecTourAward, 6);
		}
		_os.write(iZoonID, 7);
		_os.write(iEventID, 8);
		_os.write(uZoonEventTM, 9);
	}

	static java.util.List<com.yoooum.tars.yoooum.TItemInfo> cache_vecDayAward;
	static { 
		cache_vecDayAward = new java.util.ArrayList<com.yoooum.tars.yoooum.TItemInfo>();
		com.yoooum.tars.yoooum.TItemInfo var_46 = new com.yoooum.tars.yoooum.TItemInfo();
		cache_vecDayAward.add(var_46);
	}
	static java.util.List<com.yoooum.tars.yoooum.TItemInfo> cache_vecTourAward;
	static { 
		cache_vecTourAward = new java.util.ArrayList<com.yoooum.tars.yoooum.TItemInfo>();
		com.yoooum.tars.yoooum.TItemInfo var_47 = new com.yoooum.tars.yoooum.TItemInfo();
		cache_vecTourAward.add(var_47);
	}

	public void readFrom(TarsInputStream _is) {
		this.Status = _is.read(Status, 0, false);
		this.vecDayAward = (java.util.List<com.yoooum.tars.yoooum.TItemInfo>) _is.read(cache_vecDayAward, 1, false);
		this.uLastRefreshTM = _is.read(uLastRefreshTM, 2, false);
		this.AwardStatus = _is.read(AwardStatus, 3, false);
		this.uTourTM = _is.read(uTourTM, 4, false);
		this.uComeBackTM = _is.read(uComeBackTM, 5, false);
		this.vecTourAward = (java.util.List<com.yoooum.tars.yoooum.TItemInfo>) _is.read(cache_vecTourAward, 6, false);
		this.iZoonID = _is.read(iZoonID, 7, false);
		this.iEventID = _is.read(iEventID, 8, false);
		this.uZoonEventTM = _is.read(uZoonEventTM, 9, false);
	}

}
