// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TUserBaseInfo {

	@TarsStructProperty(order = 0, isRequire = false)
	public String sName = "";
	@TarsStructProperty(order = 1, isRequire = false)
	public short nGeneder = (short)0;
	@TarsStructProperty(order = 2, isRequire = false)
	public String sFaceUrl = "";
	@TarsStructProperty(order = 3, isRequire = false)
	public TDBBaseInfo BaseInfo = null;
	@TarsStructProperty(order = 4, isRequire = false)
	public String sSign = "";
	@TarsStructProperty(order = 5, isRequire = false)
	public String sSecondName = "";
	@TarsStructProperty(order = 6, isRequire = false)
	public String sFaceFrame = "";
	@TarsStructProperty(order = 7, isRequire = false)
	public int iSuffixName = 0;
	@TarsStructProperty(order = 8, isRequire = false)
	public int iCurrFaceID = 0;
	@TarsStructProperty(order = 9, isRequire = false)
	public int iCurrFrameID = 0;
	@TarsStructProperty(order = 10, isRequire = false)
	public long uiLastZeroTime = 0L;
	@TarsStructProperty(order = 11, isRequire = false)
	public java.util.List<com.yoooum.tars.yoooum.TGameData> aGameData = null;
	@TarsStructProperty(order = 12, isRequire = false)
	public int iCumulativeLoginDays = 0;

	public String getSName() {
		return sName;
	}

	public void setSName(String sName) {
		this.sName = sName;
	}

	public short getNGeneder() {
		return nGeneder;
	}

	public void setNGeneder(short nGeneder) {
		this.nGeneder = nGeneder;
	}

	public String getSFaceUrl() {
		return sFaceUrl;
	}

	public void setSFaceUrl(String sFaceUrl) {
		this.sFaceUrl = sFaceUrl;
	}

	public TDBBaseInfo getBaseInfo() {
		return BaseInfo;
	}

	public void setBaseInfo(TDBBaseInfo BaseInfo) {
		this.BaseInfo = BaseInfo;
	}

	public String getSSign() {
		return sSign;
	}

	public void setSSign(String sSign) {
		this.sSign = sSign;
	}

	public String getSSecondName() {
		return sSecondName;
	}

	public void setSSecondName(String sSecondName) {
		this.sSecondName = sSecondName;
	}

	public String getSFaceFrame() {
		return sFaceFrame;
	}

	public void setSFaceFrame(String sFaceFrame) {
		this.sFaceFrame = sFaceFrame;
	}

	public int getISuffixName() {
		return iSuffixName;
	}

	public void setISuffixName(int iSuffixName) {
		this.iSuffixName = iSuffixName;
	}

	public int getICurrFaceID() {
		return iCurrFaceID;
	}

	public void setICurrFaceID(int iCurrFaceID) {
		this.iCurrFaceID = iCurrFaceID;
	}

	public int getICurrFrameID() {
		return iCurrFrameID;
	}

	public void setICurrFrameID(int iCurrFrameID) {
		this.iCurrFrameID = iCurrFrameID;
	}

	public long getUiLastZeroTime() {
		return uiLastZeroTime;
	}

	public void setUiLastZeroTime(long uiLastZeroTime) {
		this.uiLastZeroTime = uiLastZeroTime;
	}

	public java.util.List<com.yoooum.tars.yoooum.TGameData> getAGameData() {
		return aGameData;
	}

	public void setAGameData(java.util.List<com.yoooum.tars.yoooum.TGameData> aGameData) {
		this.aGameData = aGameData;
	}

	public int getICumulativeLoginDays() {
		return iCumulativeLoginDays;
	}

	public void setICumulativeLoginDays(int iCumulativeLoginDays) {
		this.iCumulativeLoginDays = iCumulativeLoginDays;
	}

	public TUserBaseInfo() {
	}

	public TUserBaseInfo(String sName, short nGeneder, String sFaceUrl, TDBBaseInfo BaseInfo, String sSign, String sSecondName, String sFaceFrame, int iSuffixName, int iCurrFaceID, int iCurrFrameID, long uiLastZeroTime, java.util.List<com.yoooum.tars.yoooum.TGameData> aGameData, int iCumulativeLoginDays) {
		this.sName = sName;
		this.nGeneder = nGeneder;
		this.sFaceUrl = sFaceUrl;
		this.BaseInfo = BaseInfo;
		this.sSign = sSign;
		this.sSecondName = sSecondName;
		this.sFaceFrame = sFaceFrame;
		this.iSuffixName = iSuffixName;
		this.iCurrFaceID = iCurrFaceID;
		this.iCurrFrameID = iCurrFrameID;
		this.uiLastZeroTime = uiLastZeroTime;
		this.aGameData = aGameData;
		this.iCumulativeLoginDays = iCumulativeLoginDays;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(sName);
		result = prime * result + TarsUtil.hashCode(nGeneder);
		result = prime * result + TarsUtil.hashCode(sFaceUrl);
		result = prime * result + TarsUtil.hashCode(BaseInfo);
		result = prime * result + TarsUtil.hashCode(sSign);
		result = prime * result + TarsUtil.hashCode(sSecondName);
		result = prime * result + TarsUtil.hashCode(sFaceFrame);
		result = prime * result + TarsUtil.hashCode(iSuffixName);
		result = prime * result + TarsUtil.hashCode(iCurrFaceID);
		result = prime * result + TarsUtil.hashCode(iCurrFrameID);
		result = prime * result + TarsUtil.hashCode(uiLastZeroTime);
		result = prime * result + TarsUtil.hashCode(aGameData);
		result = prime * result + TarsUtil.hashCode(iCumulativeLoginDays);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TUserBaseInfo)) {
			return false;
		}
		TUserBaseInfo other = (TUserBaseInfo) obj;
		return (
			TarsUtil.equals(sName, other.sName) &&
			TarsUtil.equals(nGeneder, other.nGeneder) &&
			TarsUtil.equals(sFaceUrl, other.sFaceUrl) &&
			TarsUtil.equals(BaseInfo, other.BaseInfo) &&
			TarsUtil.equals(sSign, other.sSign) &&
			TarsUtil.equals(sSecondName, other.sSecondName) &&
			TarsUtil.equals(sFaceFrame, other.sFaceFrame) &&
			TarsUtil.equals(iSuffixName, other.iSuffixName) &&
			TarsUtil.equals(iCurrFaceID, other.iCurrFaceID) &&
			TarsUtil.equals(iCurrFrameID, other.iCurrFrameID) &&
			TarsUtil.equals(uiLastZeroTime, other.uiLastZeroTime) &&
			TarsUtil.equals(aGameData, other.aGameData) &&
			TarsUtil.equals(iCumulativeLoginDays, other.iCumulativeLoginDays) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		if (null != sName) {
			_os.write(sName, 0);
		}
		_os.write(nGeneder, 1);
		if (null != sFaceUrl) {
			_os.write(sFaceUrl, 2);
		}
		if (null != BaseInfo) {
			_os.write(BaseInfo, 3);
		}
		if (null != sSign) {
			_os.write(sSign, 4);
		}
		if (null != sSecondName) {
			_os.write(sSecondName, 5);
		}
		if (null != sFaceFrame) {
			_os.write(sFaceFrame, 6);
		}
		_os.write(iSuffixName, 7);
		_os.write(iCurrFaceID, 8);
		_os.write(iCurrFrameID, 9);
		_os.write(uiLastZeroTime, 10);
		if (null != aGameData) {
			_os.write(aGameData, 11);
		}
		_os.write(iCumulativeLoginDays, 12);
	}

	static TDBBaseInfo cache_BaseInfo;
	static { 
		cache_BaseInfo = new TDBBaseInfo();
	}
	static java.util.List<com.yoooum.tars.yoooum.TGameData> cache_aGameData;
	static { 
		cache_aGameData = new java.util.ArrayList<com.yoooum.tars.yoooum.TGameData>();
		com.yoooum.tars.yoooum.TGameData var_2 = new com.yoooum.tars.yoooum.TGameData();
		cache_aGameData.add(var_2);
	}

	public void readFrom(TarsInputStream _is) {
		this.sName = _is.readString(0, false);
		this.nGeneder = _is.read(nGeneder, 1, false);
		this.sFaceUrl = _is.readString(2, false);
		this.BaseInfo = (TDBBaseInfo) _is.read(cache_BaseInfo, 3, false);
		this.sSign = _is.readString(4, false);
		this.sSecondName = _is.readString(5, false);
		this.sFaceFrame = _is.readString(6, false);
		this.iSuffixName = _is.read(iSuffixName, 7, false);
		this.iCurrFaceID = _is.read(iCurrFaceID, 8, false);
		this.iCurrFrameID = _is.read(iCurrFrameID, 9, false);
		this.uiLastZeroTime = _is.read(uiLastZeroTime, 10, false);
		this.aGameData = (java.util.List<com.yoooum.tars.yoooum.TGameData>) _is.read(cache_aGameData, 11, false);
		this.iCumulativeLoginDays = _is.read(iCumulativeLoginDays, 12, false);
	}

}
