// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TUserOnlineState {

	@TarsStructProperty(order = 0, isRequire = true)
	public String sCondSvr = "";
	@TarsStructProperty(order = 1, isRequire = true)
	public long lConnID = 0L;
	@TarsStructProperty(order = 2, isRequire = true)
	public String sZoneSvr = "";
	@TarsStructProperty(order = 3, isRequire = true)
	public int iState = 0;
	@TarsStructProperty(order = 4, isRequire = true)
	public long lTimeStamp = 0L;
	@TarsStructProperty(order = 5, isRequire = true)
	public int iLastZoneID = 0;

	public String getSCondSvr() {
		return sCondSvr;
	}

	public void setSCondSvr(String sCondSvr) {
		this.sCondSvr = sCondSvr;
	}

	public long getLConnID() {
		return lConnID;
	}

	public void setLConnID(long lConnID) {
		this.lConnID = lConnID;
	}

	public String getSZoneSvr() {
		return sZoneSvr;
	}

	public void setSZoneSvr(String sZoneSvr) {
		this.sZoneSvr = sZoneSvr;
	}

	public int getIState() {
		return iState;
	}

	public void setIState(int iState) {
		this.iState = iState;
	}

	public long getLTimeStamp() {
		return lTimeStamp;
	}

	public void setLTimeStamp(long lTimeStamp) {
		this.lTimeStamp = lTimeStamp;
	}

	public int getILastZoneID() {
		return iLastZoneID;
	}

	public void setILastZoneID(int iLastZoneID) {
		this.iLastZoneID = iLastZoneID;
	}

	public TUserOnlineState() {
	}

	public TUserOnlineState(String sCondSvr, long lConnID, String sZoneSvr, int iState, long lTimeStamp, int iLastZoneID) {
		this.sCondSvr = sCondSvr;
		this.lConnID = lConnID;
		this.sZoneSvr = sZoneSvr;
		this.iState = iState;
		this.lTimeStamp = lTimeStamp;
		this.iLastZoneID = iLastZoneID;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(sCondSvr);
		result = prime * result + TarsUtil.hashCode(lConnID);
		result = prime * result + TarsUtil.hashCode(sZoneSvr);
		result = prime * result + TarsUtil.hashCode(iState);
		result = prime * result + TarsUtil.hashCode(lTimeStamp);
		result = prime * result + TarsUtil.hashCode(iLastZoneID);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TUserOnlineState)) {
			return false;
		}
		TUserOnlineState other = (TUserOnlineState) obj;
		return (
			TarsUtil.equals(sCondSvr, other.sCondSvr) &&
			TarsUtil.equals(lConnID, other.lConnID) &&
			TarsUtil.equals(sZoneSvr, other.sZoneSvr) &&
			TarsUtil.equals(iState, other.iState) &&
			TarsUtil.equals(lTimeStamp, other.lTimeStamp) &&
			TarsUtil.equals(iLastZoneID, other.iLastZoneID) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(sCondSvr, 0);
		_os.write(lConnID, 1);
		_os.write(sZoneSvr, 2);
		_os.write(iState, 3);
		_os.write(lTimeStamp, 4);
		_os.write(iLastZoneID, 5);
	}


	public void readFrom(TarsInputStream _is) {
		this.sCondSvr = _is.readString(0, true);
		this.lConnID = _is.read(lConnID, 1, true);
		this.sZoneSvr = _is.readString(2, true);
		this.iState = _is.read(iState, 3, true);
		this.lTimeStamp = _is.read(lTimeStamp, 4, true);
		this.iLastZoneID = _is.read(iLastZoneID, 5, true);
	}

}
