// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.yoooum;

public enum ADD_MATCH_ROOM_TYPE {

	ADD_MATCH_ROOM_TYPE_DEFAUT(0),
	ADD_MATCH_ROOM_TYPE_BE_INVITE(1),
	ADD_MATCH_ROOM_TYPE_RE_ADD(2),
	ADD_MATCH_ROOM_TYPE_FAST_ADD(3);

	private final int value;

	private ADD_MATCH_ROOM_TYPE(int value) {
		this.value = value;
	}

	public int value() {
		return this.value;
	}

	@Override
	public String toString() {
		return this.name() + ":" + this.value;
	}

	public static ADD_MATCH_ROOM_TYPE convert(int value) {
		for(ADD_MATCH_ROOM_TYPE v : values()) {
			if(v.value() == value) {
				return v;
			}
		}
		return null;
	}
}
