// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.yoooum;

public enum ALLOCATE_TOOM_TYPE {

	ALLOCATE_TOOM_TYPE_CREATE_ROOM(1),
	ALLOCATE_TOOM_TYPE_MATCH(2),
	ALLOCATE_TOOM_TYPE_AI_1V5(3);

	private final int value;

	private ALLOCATE_TOOM_TYPE(int value) {
		this.value = value;
	}

	public int value() {
		return this.value;
	}

	@Override
	public String toString() {
		return this.name() + ":" + this.value;
	}

	public static ALLOCATE_TOOM_TYPE convert(int value) {
		for(ALLOCATE_TOOM_TYPE v : values()) {
			if(v.value() == value) {
				return v;
			}
		}
		return null;
	}
}
