// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.yoooum;

public enum CS_CONNECT_TYPE {

	CS_CONNECT_TYPE_NEW(1),
	CS_CONNECT_TYPE_RECONNECT(2);

	private final int value;

	private CS_CONNECT_TYPE(int value) {
		this.value = value;
	}

	public int value() {
		return this.value;
	}

	@Override
	public String toString() {
		return this.name() + ":" + this.value;
	}

	public static CS_CONNECT_TYPE convert(int value) {
		for(CS_CONNECT_TYPE v : values()) {
			if(v.value() == value) {
				return v;
			}
		}
		return null;
	}
}
