// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.yoooum;

public enum E_CLIENT_VERSION_UPDATE_TYPE {

	E_CLIENT_VERSION_UPDATE_TYPE_NO(0),
	E_CLIENT_VERSION_UPDATE_TYPE_FORCE(1),
	E_CLIENT_VERSION_UPDATE_TYPE_OPTION(2);

	private final int value;

	private E_CLIENT_VERSION_UPDATE_TYPE(int value) {
		this.value = value;
	}

	public int value() {
		return this.value;
	}

	@Override
	public String toString() {
		return this.name() + ":" + this.value;
	}

	public static E_CLIENT_VERSION_UPDATE_TYPE convert(int value) {
		for(E_CLIENT_VERSION_UPDATE_TYPE v : values()) {
			if(v.value() == value) {
				return v;
			}
		}
		return null;
	}
}
