// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.yoooum;

public enum E_DEVICE_QUALITY_TYPE {

	E_DEVICE_QUALITY_NORMAL(0),
	E_DEVICE_QUALITY_HIGHT(1);

	private final int value;

	private E_DEVICE_QUALITY_TYPE(int value) {
		this.value = value;
	}

	public int value() {
		return this.value;
	}

	@Override
	public String toString() {
		return this.name() + ":" + this.value;
	}

	public static E_DEVICE_QUALITY_TYPE convert(int value) {
		for(E_DEVICE_QUALITY_TYPE v : values()) {
			if(v.value() == value) {
				return v;
			}
		}
		return null;
	}
}
