// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.yoooum;

public enum E_LANGUAGE_TYPE {

	china(0),
	usa(1),
	korea(2),
	japan(3),
	thailand(4),
	taiwan(5),
	vietnam(6),
	singapore(7),
	cambodia(8),
	malaysia(9);

	private final int value;

	private E_LANGUAGE_TYPE(int value) {
		this.value = value;
	}

	public int value() {
		return this.value;
	}

	@Override
	public String toString() {
		return this.name() + ":" + this.value;
	}

	public static E_LANGUAGE_TYPE convert(int value) {
		for(E_LANGUAGE_TYPE v : values()) {
			if(v.value() == value) {
				return v;
			}
		}
		return null;
	}
}
