// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.yoooum;

public enum E_LOGIN_TYPE {

	E_LOGIN_TYPE_VERIFY_PLAT(0),
	E_LOGIN_TYPE_PHONE_NUMBER(1),
	E_LOGIN_TYPE_USERNAME(2),
	E_LOGIN_TYPE_QUICK(3);

	private final int value;

	private E_LOGIN_TYPE(int value) {
		this.value = value;
	}

	public int value() {
		return this.value;
	}

	@Override
	public String toString() {
		return this.name() + ":" + this.value;
	}

	public static E_LOGIN_TYPE convert(int value) {
		for(E_LOGIN_TYPE v : values()) {
			if(v.value() == value) {
				return v;
			}
		}
		return null;
	}
}
