// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.yoooum;

public enum E_MOBILE_PLAT_TYPE {

	E_MOBILE_PLAT_TYPE_INVALID(0),
	E_MOBILE_PLAT_TYPE_ANDROID(1),
	E_MOBILE_PLAT_TYPE_IOS(2),
	E_MOBILE_PLAT_TYPE_PC(3);

	private final int value;

	private E_MOBILE_PLAT_TYPE(int value) {
		this.value = value;
	}

	public int value() {
		return this.value;
	}

	@Override
	public String toString() {
		return this.name() + ":" + this.value;
	}

	public static E_MOBILE_PLAT_TYPE convert(int value) {
		for(E_MOBILE_PLAT_TYPE v : values()) {
			if(v.value() == value) {
				return v;
			}
		}
		return null;
	}
}
