// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.yoooum;

public enum E_MODE_TYPE {

	MODE_TYPE_NONE(0),
	MODE_TYPE_MULTIPLAYER_RATE(1),
	MODE_TYPE_MAX(2);

	private final int value;

	private E_MODE_TYPE(int value) {
		this.value = value;
	}

	public int value() {
		return this.value;
	}

	@Override
	public String toString() {
		return this.name() + ":" + this.value;
	}

	public static E_MODE_TYPE convert(int value) {
		for(E_MODE_TYPE v : values()) {
			if(v.value() == value) {
				return v;
			}
		}
		return null;
	}
}
