// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.yoooum;

public enum E_MSG_TYPE {

	E_MSG_TYPE_REQUEST(0),
	E_MSG_TYPE_RESPONSE(1),
	E_MSG_TYPE_NOTIFY(2);

	private final int value;

	private E_MSG_TYPE(int value) {
		this.value = value;
	}

	public int value() {
		return this.value;
	}

	@Override
	public String toString() {
		return this.name() + ":" + this.value;
	}

	public static E_MSG_TYPE convert(int value) {
		for(E_MSG_TYPE v : values()) {
			if(v.value() == value) {
				return v;
			}
		}
		return null;
	}
}
