// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.yoooum;

public enum E_OPEN_PLAT_TYPE {

	E_OPEN_PLAT_TYPE_INVALID(0),
	E_OPEN_PLAT_TYPE_IOS(1),
	E_OPEN_PLAT_TYPE_SHANGYOU(2),
	E_OPEN_PLAT_TYPE_OPPO(11),
	E_OPEN_PLAT_TYPE_VIVO(12),
	E_OPEN_PLAT_TYPE_HUAWEI(13),
	E_OPEN_PLAT_TYPE_9YOU(14),
	E_OPEN_PLAT_TYPE_XIAOMI(16),
	E_OPEN_PLAT_TYPE_360(17),
	E_OPEN_PLAT_TYPE_BAIDU(18),
	E_OPEN_PLAT_TYPE_MEIZU(19),
	E_OPEN_PLAT_TYPE_LENOVO(20),
	E_OPEN_PLAT_TYPE_KUPAI(21),
	E_OPEN_PLAT_TYPE_JL(22),
	E_OPEN_PLAT_TYPE_YINGYONGBAO(23),
	E_OPEN_PLAT_TYPE_4399(26),
	E_OPEN_PLAT_TYPE_NUBIA(29),
	E_OPEN_PLAT_TYPE_BILIBILI(30),
	E_OPEN_PLAT_TYPE_PC(40),
	E_OPEN_PLAT_TYPE_YOOOUM(41),
	E_OPEN_PLAT_TYPE_WECHAT(42),
	E_OPEN_PLAT_TYPE_QQ(43),
	E_OPEN_PLAT_TYPE_GUEST(44),
	E_OPEN_PLAT_TYPE_MINIGAME(45),
	E_OPEN_PLAT_TYPE_LJ(47),
	E_OPEN_PLAT_TYPE_FACEBOOK(48),
	E_OPEN_PLAT_TYPE_GOOGLE(49),
	E_OPEN_PLAT_TYPE_GARENA(50),
	E_OPEN_PLAT_TYPE_SY_MAILIANG(100),
	E_OPEN_PLAT_TYPE_TAPTAP(101),
	E_OPEN_PLAT_TYPE_HYKB(102),
	E_OPEN_PLAT_TYPE_SY_MAILIANG2(103),
	E_OPEN_PLAT_TYPE_END(150);

	private final int value;

	private E_OPEN_PLAT_TYPE(int value) {
		this.value = value;
	}

	public int value() {
		return this.value;
	}

	@Override
	public String toString() {
		return this.name() + ":" + this.value;
	}

	public static E_OPEN_PLAT_TYPE convert(int value) {
		for(E_OPEN_PLAT_TYPE v : values()) {
			if(v.value() == value) {
				return v;
			}
		}
		return null;
	}
}
