// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.yoooum;

public enum E_PROPERTIES_OPER {

	E_PROPERTIES_OPER_EQUAL(0),
	E_PROPERTIES_OPER_ADD(1),
	E_PROPERTIES_OPER_DEL(2);

	private final int value;

	private E_PROPERTIES_OPER(int value) {
		this.value = value;
	}

	public int value() {
		return this.value;
	}

	@Override
	public String toString() {
		return this.name() + ":" + this.value;
	}

	public static E_PROPERTIES_OPER convert(int value) {
		for(E_PROPERTIES_OPER v : values()) {
			if(v.value() == value) {
				return v;
			}
		}
		return null;
	}
}
