// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.yoooum;

public enum E_SERVER_STATUE {

	E_SERVER_STATUE_NORMAL(0),
	E_SERVER_STATUE_FULL(1),
	E_SERVER_STATUE_MAINTAIN(2),
	E_SERVER_STATUE_NORANDNEW(3),
	E_SERVER_STATUE_NORANDHOT(4),
	E_SERVER_STATUE_NORANDREC(5),
	E_SERVER_STATUE_FULLANDNEW(6),
	E_SERVER_STATUE_FULLANDHOT(7);

	private final int value;

	private E_SERVER_STATUE(int value) {
		this.value = value;
	}

	public int value() {
		return this.value;
	}

	@Override
	public String toString() {
		return this.name() + ":" + this.value;
	}

	public static E_SERVER_STATUE convert(int value) {
		for(E_SERVER_STATUE v : values()) {
			if(v.value() == value) {
				return v;
			}
		}
		return null;
	}
}
