// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.yoooum;

public enum E_SEX {

	E_SEX_INVALID(0),
	E_SEX_MAN(1),
	E_SEX_WOMAN(2);

	private final int value;

	private E_SEX(int value) {
		this.value = value;
	}

	public int value() {
		return this.value;
	}

	@Override
	public String toString() {
		return this.name() + ":" + this.value;
	}

	public static E_SEX convert(int value) {
		for(E_SEX v : values()) {
			if(v.value() == value) {
				return v;
			}
		}
		return null;
	}
}
