// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.yoooum;

public enum E_TASK_TYPE {

	E_TASK_TYPE_MAIN(1),
	E_TASK_TYPE_DAY(2),
	E_TASK_TYPE_ZOON(3);

	private final int value;

	private E_TASK_TYPE(int value) {
		this.value = value;
	}

	public int value() {
		return this.value;
	}

	@Override
	public String toString() {
		return this.name() + ":" + this.value;
	}

	public static E_TASK_TYPE convert(int value) {
		for(E_TASK_TYPE v : values()) {
			if(v.value() == value) {
				return v;
			}
		}
		return null;
	}
}
