// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.yoooum;

public enum E_TASK_STATE {

	E_TASK_STATE_INITIALIZE(0),
	E_TASK_STATE_PROGRESS(1),
	E_TASK_STATE_FINISHED(2),
	E_TASK_STATE_ALREADY(3);

	private final int value;

	private E_TASK_STATE(int value) {
		this.value = value;
	}

	public int value() {
		return this.value;
	}

	@Override
	public String toString() {
		return this.name() + ":" + this.value;
	}

	public static E_TASK_STATE convert(int value) {
		for(E_TASK_STATE v : values()) {
			if(v.value() == value) {
				return v;
			}
		}
		return null;
	}
}
