// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.yoooum;

public enum E_TASK_AWARD_FLAG {

	E_TASK_AWARD_FLAG_LOCK(0),
	E_TASK_AWARD_FLAG_UNABLE(1),
	E_TASK_AWARD_FLAG_ABLE(2),
	E_TASK_AWARD_FLAG_ALREADY(3);

	private final int value;

	private E_TASK_AWARD_FLAG(int value) {
		this.value = value;
	}

	public int value() {
		return this.value;
	}

	@Override
	public String toString() {
		return this.name() + ":" + this.value;
	}

	public static E_TASK_AWARD_FLAG convert(int value) {
		for(E_TASK_AWARD_FLAG v : values()) {
			if(v.value() == value) {
				return v;
			}
		}
		return null;
	}
}
