// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.yoooum;

public enum E_TASK_TARGET_TYPE {

	E_TASK_TARGET_INVAILD(0),
	E_TASK_TARGET_DIALOG(1001),
	E_TASK_TARGET_KILL(1002),
	E_TASK_TARGET_GAME(1003),
	E_TASK_TARGET_RESCUE(1004),
	E_TASK_TARGET_COST(1005),
	E_TASK_TARGET_ONLINE_GAME(1006);

	private final int value;

	private E_TASK_TARGET_TYPE(int value) {
		this.value = value;
	}

	public int value() {
		return this.value;
	}

	@Override
	public String toString() {
		return this.name() + ":" + this.value;
	}

	public static E_TASK_TARGET_TYPE convert(int value) {
		for(E_TASK_TARGET_TYPE v : values()) {
			if(v.value() == value) {
				return v;
			}
		}
		return null;
	}
}
