// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.yoooum;

public enum E_WORKSHOP_TYPE {

	E_WORKSHOP_TYPE_PROP(0),
	E_ITEM_USE_TYPE_SMITHY(1),
	E_ITEM_USE_TYPE_KITCHEN(2),
	E_WORKSHOP_TYPE_MAX(3);

	private final int value;

	private E_WORKSHOP_TYPE(int value) {
		this.value = value;
	}

	public int value() {
		return this.value;
	}

	@Override
	public String toString() {
		return this.name() + ":" + this.value;
	}

	public static E_WORKSHOP_TYPE convert(int value) {
		for(E_WORKSHOP_TYPE v : values()) {
			if(v.value() == value) {
				return v;
			}
		}
		return null;
	}
}
