// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.yoooum;

public enum EN_ANIMAL_STATUS {

	EN_ANIMAL_STATUS_SMALL(0),
	EN_ANIMAL_STATUS_MID(1),
	EN_ANIMAL_STATUS_GROWN(2);

	private final int value;

	private EN_ANIMAL_STATUS(int value) {
		this.value = value;
	}

	public int value() {
		return this.value;
	}

	@Override
	public String toString() {
		return this.name() + ":" + this.value;
	}

	public static EN_ANIMAL_STATUS convert(int value) {
		for(EN_ANIMAL_STATUS v : values()) {
			if(v.value() == value) {
				return v;
			}
		}
		return null;
	}
}
