// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.yoooum;

/*************************************************************************************/
public enum ENETWORK_TYPE {

	NETWORK_TYPE_INVALID(0),
	NETWORK_TYPE_2G(1),
	NETWORK_TYPE_3G(2),
	NETWORK_TYPE_4G(3),
	NETWORK_TYPE_WIFI(4),
	NETWORK_TYPE_5G(5);

	private final int value;

	private ENETWORK_TYPE(int value) {
		this.value = value;
	}

	public int value() {
		return this.value;
	}

	@Override
	public String toString() {
		return this.name() + ":" + this.value;
	}

	public static ENETWORK_TYPE convert(int value) {
		for(ENETWORK_TYPE v : values()) {
			if(v.value() == value) {
				return v;
			}
		}
		return null;
	}
}
