// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.yoooum;

public enum ENUM_ACT_STAT_TYPE {

	ENUM_ACT_STAT_KILL(1),
	ENUM_ACT_STAT_SAY_LOVE(2),
	ENUM_ACT_STAT_TOTAL_GRAB_COINS(3),
	ENUM_ACT_STAT_MAX(4);

	private final int value;

	private ENUM_ACT_STAT_TYPE(int value) {
		this.value = value;
	}

	public int value() {
		return this.value;
	}

	@Override
	public String toString() {
		return this.name() + ":" + this.value;
	}

	public static ENUM_ACT_STAT_TYPE convert(int value) {
		for(ENUM_ACT_STAT_TYPE v : values()) {
			if(v.value() == value) {
				return v;
			}
		}
		return null;
	}
}
