// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.yoooum;

import com.qq.tars.rpc.protocol.tars.support.TarsAbstractCallback;

public abstract class IdipServantPrxCallback extends TarsAbstractCallback {

	public abstract void callback_PlatSendMail(int ret, java.util.List<com.yoooum.tars.yoooum.TAccountID> vecSuccAccountID, java.util.List<com.yoooum.tars.yoooum.TAccountID> vecFailAccountID);

	public abstract void callback_SendServerMail(int ret);

}
