// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.yoooum;

public enum PVP_KICK_OFF_REASON {

	PVP_KICK_OFF_REASON_LOADING_SLOW(1),
	PVP_KICK_OFF_REASON_EXIT_ROOM_DURING_START(2),
	PVP_KICK_OFF_REASON_READY_SLOW(3);

	private final int value;

	private PVP_KICK_OFF_REASON(int value) {
		this.value = value;
	}

	public int value() {
		return this.value;
	}

	@Override
	public String toString() {
		return this.name() + ":" + this.value;
	}

	public static PVP_KICK_OFF_REASON convert(int value) {
		for(PVP_KICK_OFF_REASON v : values()) {
			if(v.value() == value) {
				return v;
			}
		}
		return null;
	}
}
