// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.yoooum;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TAnimalSlot {

	@TarsStructProperty(order = 0, isRequire = false)
	public int iSlotID = 0;
	@TarsStructProperty(order = 1, isRequire = false)
	public int iAnimalID = 0;
	@TarsStructProperty(order = 2, isRequire = false)
	public int iAnimalStatus = 0;
	@TarsStructProperty(order = 3, isRequire = false)
	public long uiNextStageTime = 0L;
	@TarsStructProperty(order = 4, isRequire = false)
	public long uiNeedRefreshTime = 0L;
	@TarsStructProperty(order = 5, isRequire = false)
	public boolean bIsAte = false;

	public int getISlotID() {
		return iSlotID;
	}

	public void setISlotID(int iSlotID) {
		this.iSlotID = iSlotID;
	}

	public int getIAnimalID() {
		return iAnimalID;
	}

	public void setIAnimalID(int iAnimalID) {
		this.iAnimalID = iAnimalID;
	}

	public int getIAnimalStatus() {
		return iAnimalStatus;
	}

	public void setIAnimalStatus(int iAnimalStatus) {
		this.iAnimalStatus = iAnimalStatus;
	}

	public long getUiNextStageTime() {
		return uiNextStageTime;
	}

	public void setUiNextStageTime(long uiNextStageTime) {
		this.uiNextStageTime = uiNextStageTime;
	}

	public long getUiNeedRefreshTime() {
		return uiNeedRefreshTime;
	}

	public void setUiNeedRefreshTime(long uiNeedRefreshTime) {
		this.uiNeedRefreshTime = uiNeedRefreshTime;
	}

	public boolean getBIsAte() {
		return bIsAte;
	}

	public void setBIsAte(boolean bIsAte) {
		this.bIsAte = bIsAte;
	}

	public TAnimalSlot() {
	}

	public TAnimalSlot(int iSlotID, int iAnimalID, int iAnimalStatus, long uiNextStageTime, long uiNeedRefreshTime, boolean bIsAte) {
		this.iSlotID = iSlotID;
		this.iAnimalID = iAnimalID;
		this.iAnimalStatus = iAnimalStatus;
		this.uiNextStageTime = uiNextStageTime;
		this.uiNeedRefreshTime = uiNeedRefreshTime;
		this.bIsAte = bIsAte;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(iSlotID);
		result = prime * result + TarsUtil.hashCode(iAnimalID);
		result = prime * result + TarsUtil.hashCode(iAnimalStatus);
		result = prime * result + TarsUtil.hashCode(uiNextStageTime);
		result = prime * result + TarsUtil.hashCode(uiNeedRefreshTime);
		result = prime * result + TarsUtil.hashCode(bIsAte);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TAnimalSlot)) {
			return false;
		}
		TAnimalSlot other = (TAnimalSlot) obj;
		return (
			TarsUtil.equals(iSlotID, other.iSlotID) &&
			TarsUtil.equals(iAnimalID, other.iAnimalID) &&
			TarsUtil.equals(iAnimalStatus, other.iAnimalStatus) &&
			TarsUtil.equals(uiNextStageTime, other.uiNextStageTime) &&
			TarsUtil.equals(uiNeedRefreshTime, other.uiNeedRefreshTime) &&
			TarsUtil.equals(bIsAte, other.bIsAte) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(iSlotID, 0);
		_os.write(iAnimalID, 1);
		_os.write(iAnimalStatus, 2);
		_os.write(uiNextStageTime, 3);
		_os.write(uiNeedRefreshTime, 4);
		_os.write(bIsAte, 5);
	}


	public void readFrom(TarsInputStream _is) {
		this.iSlotID = _is.read(iSlotID, 0, false);
		this.iAnimalID = _is.read(iAnimalID, 1, false);
		this.iAnimalStatus = _is.read(iAnimalStatus, 2, false);
		this.uiNextStageTime = _is.read(uiNextStageTime, 3, false);
		this.uiNeedRefreshTime = _is.read(uiNeedRefreshTime, 4, false);
		this.bIsAte = _is.read(bIsAte, 5, false);
	}

}
