// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.yoooum;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TBagSlot {

	@TarsStructProperty(order = 0, isRequire = false)
	public int iItemID = 0;
	@TarsStructProperty(order = 1, isRequire = false)
	public int iItemCount = 0;
	@TarsStructProperty(order = 2, isRequire = false)
	public short usIndex = (short)0;
	@TarsStructProperty(order = 3, isRequire = false)
	public short shWear = (short)0;
	@TarsStructProperty(order = 4, isRequire = false)
	public long lUniqID = 0L;

	public int getIItemID() {
		return iItemID;
	}

	public void setIItemID(int iItemID) {
		this.iItemID = iItemID;
	}

	public int getIItemCount() {
		return iItemCount;
	}

	public void setIItemCount(int iItemCount) {
		this.iItemCount = iItemCount;
	}

	public short getUsIndex() {
		return usIndex;
	}

	public void setUsIndex(short usIndex) {
		this.usIndex = usIndex;
	}

	public short getShWear() {
		return shWear;
	}

	public void setShWear(short shWear) {
		this.shWear = shWear;
	}

	public long getLUniqID() {
		return lUniqID;
	}

	public void setLUniqID(long lUniqID) {
		this.lUniqID = lUniqID;
	}

	public TBagSlot() {
	}

	public TBagSlot(int iItemID, int iItemCount, short usIndex, short shWear, long lUniqID) {
		this.iItemID = iItemID;
		this.iItemCount = iItemCount;
		this.usIndex = usIndex;
		this.shWear = shWear;
		this.lUniqID = lUniqID;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(iItemID);
		result = prime * result + TarsUtil.hashCode(iItemCount);
		result = prime * result + TarsUtil.hashCode(usIndex);
		result = prime * result + TarsUtil.hashCode(shWear);
		result = prime * result + TarsUtil.hashCode(lUniqID);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TBagSlot)) {
			return false;
		}
		TBagSlot other = (TBagSlot) obj;
		return (
			TarsUtil.equals(iItemID, other.iItemID) &&
			TarsUtil.equals(iItemCount, other.iItemCount) &&
			TarsUtil.equals(usIndex, other.usIndex) &&
			TarsUtil.equals(shWear, other.shWear) &&
			TarsUtil.equals(lUniqID, other.lUniqID) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(iItemID, 0);
		_os.write(iItemCount, 1);
		_os.write(usIndex, 2);
		_os.write(shWear, 3);
		_os.write(lUniqID, 4);
	}


	public void readFrom(TarsInputStream _is) {
		this.iItemID = _is.read(iItemID, 0, false);
		this.iItemCount = _is.read(iItemCount, 1, false);
		this.usIndex = _is.read(usIndex, 2, false);
		this.shWear = _is.read(shWear, 3, false);
		this.lUniqID = _is.read(lUniqID, 4, false);
	}

}
