// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.yoooum;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TBaseNpcInfo {

	@TarsStructProperty(order = 0, isRequire = false)
	public int iNpcID = 0;
	@TarsStructProperty(order = 1, isRequire = false)
	public int iFavor = 0;
	@TarsStructProperty(order = 2, isRequire = false)
	public int iLvl = 0;
	@TarsStructProperty(order = 3, isRequire = false)
	public long lKnowTM = 0L;
	@TarsStructProperty(order = 4, isRequire = false)
	public short nFavorTimes = (short)0;
	@TarsStructProperty(order = 5, isRequire = false)
	public long lLastFavorTM = 0L;

	public int getINpcID() {
		return iNpcID;
	}

	public void setINpcID(int iNpcID) {
		this.iNpcID = iNpcID;
	}

	public int getIFavor() {
		return iFavor;
	}

	public void setIFavor(int iFavor) {
		this.iFavor = iFavor;
	}

	public int getILvl() {
		return iLvl;
	}

	public void setILvl(int iLvl) {
		this.iLvl = iLvl;
	}

	public long getLKnowTM() {
		return lKnowTM;
	}

	public void setLKnowTM(long lKnowTM) {
		this.lKnowTM = lKnowTM;
	}

	public short getNFavorTimes() {
		return nFavorTimes;
	}

	public void setNFavorTimes(short nFavorTimes) {
		this.nFavorTimes = nFavorTimes;
	}

	public long getLLastFavorTM() {
		return lLastFavorTM;
	}

	public void setLLastFavorTM(long lLastFavorTM) {
		this.lLastFavorTM = lLastFavorTM;
	}

	public TBaseNpcInfo() {
	}

	public TBaseNpcInfo(int iNpcID, int iFavor, int iLvl, long lKnowTM, short nFavorTimes, long lLastFavorTM) {
		this.iNpcID = iNpcID;
		this.iFavor = iFavor;
		this.iLvl = iLvl;
		this.lKnowTM = lKnowTM;
		this.nFavorTimes = nFavorTimes;
		this.lLastFavorTM = lLastFavorTM;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(iNpcID);
		result = prime * result + TarsUtil.hashCode(iFavor);
		result = prime * result + TarsUtil.hashCode(iLvl);
		result = prime * result + TarsUtil.hashCode(lKnowTM);
		result = prime * result + TarsUtil.hashCode(nFavorTimes);
		result = prime * result + TarsUtil.hashCode(lLastFavorTM);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TBaseNpcInfo)) {
			return false;
		}
		TBaseNpcInfo other = (TBaseNpcInfo) obj;
		return (
			TarsUtil.equals(iNpcID, other.iNpcID) &&
			TarsUtil.equals(iFavor, other.iFavor) &&
			TarsUtil.equals(iLvl, other.iLvl) &&
			TarsUtil.equals(lKnowTM, other.lKnowTM) &&
			TarsUtil.equals(nFavorTimes, other.nFavorTimes) &&
			TarsUtil.equals(lLastFavorTM, other.lLastFavorTM) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(iNpcID, 0);
		_os.write(iFavor, 1);
		_os.write(iLvl, 2);
		_os.write(lKnowTM, 3);
		_os.write(nFavorTimes, 4);
		_os.write(lLastFavorTM, 5);
	}


	public void readFrom(TarsInputStream _is) {
		this.iNpcID = _is.read(iNpcID, 0, false);
		this.iFavor = _is.read(iFavor, 1, false);
		this.iLvl = _is.read(iLvl, 2, false);
		this.lKnowTM = _is.read(lKnowTM, 3, false);
		this.nFavorTimes = _is.read(nFavorTimes, 4, false);
		this.lLastFavorTM = _is.read(lLastFavorTM, 5, false);
	}

}
