// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.yoooum;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TEndpoint {

	@TarsStructProperty(order = 0, isRequire = false)
	public String sIP = "";
	@TarsStructProperty(order = 1, isRequire = false)
	public int iPort = 0;

	public String getSIP() {
		return sIP;
	}

	public void setSIP(String sIP) {
		this.sIP = sIP;
	}

	public int getIPort() {
		return iPort;
	}

	public void setIPort(int iPort) {
		this.iPort = iPort;
	}

	public TEndpoint() {
	}

	public TEndpoint(String sIP, int iPort) {
		this.sIP = sIP;
		this.iPort = iPort;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(sIP);
		result = prime * result + TarsUtil.hashCode(iPort);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TEndpoint)) {
			return false;
		}
		TEndpoint other = (TEndpoint) obj;
		return (
			TarsUtil.equals(sIP, other.sIP) &&
			TarsUtil.equals(iPort, other.iPort) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		if (null != sIP) {
			_os.write(sIP, 0);
		}
		_os.write(iPort, 1);
	}


	public void readFrom(TarsInputStream _is) {
		this.sIP = _is.readString(0, false);
		this.iPort = _is.read(iPort, 1, false);
	}

}
