// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.yoooum;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TEquipmentItem {

	@TarsStructProperty(order = 0, isRequire = false)
	public String sUniqueID = "";
	@TarsStructProperty(order = 1, isRequire = false)
	public int iEquipID = 0;
	@TarsStructProperty(order = 2, isRequire = false)
	public short nLevel = (short)0;
	@TarsStructProperty(order = 3, isRequire = false)
	public short nPos = (short)0;
	@TarsStructProperty(order = 4, isRequire = false)
	public boolean bNew = false;

	public String getSUniqueID() {
		return sUniqueID;
	}

	public void setSUniqueID(String sUniqueID) {
		this.sUniqueID = sUniqueID;
	}

	public int getIEquipID() {
		return iEquipID;
	}

	public void setIEquipID(int iEquipID) {
		this.iEquipID = iEquipID;
	}

	public short getNLevel() {
		return nLevel;
	}

	public void setNLevel(short nLevel) {
		this.nLevel = nLevel;
	}

	public short getNPos() {
		return nPos;
	}

	public void setNPos(short nPos) {
		this.nPos = nPos;
	}

	public boolean getBNew() {
		return bNew;
	}

	public void setBNew(boolean bNew) {
		this.bNew = bNew;
	}

	public TEquipmentItem() {
	}

	public TEquipmentItem(String sUniqueID, int iEquipID, short nLevel, short nPos, boolean bNew) {
		this.sUniqueID = sUniqueID;
		this.iEquipID = iEquipID;
		this.nLevel = nLevel;
		this.nPos = nPos;
		this.bNew = bNew;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(sUniqueID);
		result = prime * result + TarsUtil.hashCode(iEquipID);
		result = prime * result + TarsUtil.hashCode(nLevel);
		result = prime * result + TarsUtil.hashCode(nPos);
		result = prime * result + TarsUtil.hashCode(bNew);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TEquipmentItem)) {
			return false;
		}
		TEquipmentItem other = (TEquipmentItem) obj;
		return (
			TarsUtil.equals(sUniqueID, other.sUniqueID) &&
			TarsUtil.equals(iEquipID, other.iEquipID) &&
			TarsUtil.equals(nLevel, other.nLevel) &&
			TarsUtil.equals(nPos, other.nPos) &&
			TarsUtil.equals(bNew, other.bNew) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		if (null != sUniqueID) {
			_os.write(sUniqueID, 0);
		}
		_os.write(iEquipID, 1);
		_os.write(nLevel, 2);
		_os.write(nPos, 3);
		_os.write(bNew, 4);
	}


	public void readFrom(TarsInputStream _is) {
		this.sUniqueID = _is.readString(0, false);
		this.iEquipID = _is.read(iEquipID, 1, false);
		this.nLevel = _is.read(nLevel, 2, false);
		this.nPos = _is.read(nPos, 3, false);
		this.bNew = _is.read(bNew, 4, false);
	}

}
