// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.yoooum;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TEquipID {

	@TarsStructProperty(order = 0, isRequire = false)
	public int iEquipID = 0;
	@TarsStructProperty(order = 1, isRequire = false)
	public String sUniqID = "";

	public int getIEquipID() {
		return iEquipID;
	}

	public void setIEquipID(int iEquipID) {
		this.iEquipID = iEquipID;
	}

	public String getSUniqID() {
		return sUniqID;
	}

	public void setSUniqID(String sUniqID) {
		this.sUniqID = sUniqID;
	}

	public TEquipID() {
	}

	public TEquipID(int iEquipID, String sUniqID) {
		this.iEquipID = iEquipID;
		this.sUniqID = sUniqID;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(iEquipID);
		result = prime * result + TarsUtil.hashCode(sUniqID);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TEquipID)) {
			return false;
		}
		TEquipID other = (TEquipID) obj;
		return (
			TarsUtil.equals(iEquipID, other.iEquipID) &&
			TarsUtil.equals(sUniqID, other.sUniqID) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(iEquipID, 0);
		if (null != sUniqID) {
			_os.write(sUniqID, 1);
		}
	}


	public void readFrom(TarsInputStream _is) {
		this.iEquipID = _is.read(iEquipID, 0, false);
		this.sUniqID = _is.readString(1, false);
	}

}
