// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.yoooum;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TGameData {

	@TarsStructProperty(order = 0, isRequire = false)
	public int iRound = 0;
	@TarsStructProperty(order = 1, isRequire = false)
	public int iWin = 0;
	@TarsStructProperty(order = 2, isRequire = false)
	public int iFail = 0;
	@TarsStructProperty(order = 3, isRequire = false)
	public int iChapterID = 0;
	@TarsStructProperty(order = 4, isRequire = false)
	public int iSectionID = 0;

	public int getIRound() {
		return iRound;
	}

	public void setIRound(int iRound) {
		this.iRound = iRound;
	}

	public int getIWin() {
		return iWin;
	}

	public void setIWin(int iWin) {
		this.iWin = iWin;
	}

	public int getIFail() {
		return iFail;
	}

	public void setIFail(int iFail) {
		this.iFail = iFail;
	}

	public int getIChapterID() {
		return iChapterID;
	}

	public void setIChapterID(int iChapterID) {
		this.iChapterID = iChapterID;
	}

	public int getISectionID() {
		return iSectionID;
	}

	public void setISectionID(int iSectionID) {
		this.iSectionID = iSectionID;
	}

	public TGameData() {
	}

	public TGameData(int iRound, int iWin, int iFail, int iChapterID, int iSectionID) {
		this.iRound = iRound;
		this.iWin = iWin;
		this.iFail = iFail;
		this.iChapterID = iChapterID;
		this.iSectionID = iSectionID;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(iRound);
		result = prime * result + TarsUtil.hashCode(iWin);
		result = prime * result + TarsUtil.hashCode(iFail);
		result = prime * result + TarsUtil.hashCode(iChapterID);
		result = prime * result + TarsUtil.hashCode(iSectionID);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TGameData)) {
			return false;
		}
		TGameData other = (TGameData) obj;
		return (
			TarsUtil.equals(iRound, other.iRound) &&
			TarsUtil.equals(iWin, other.iWin) &&
			TarsUtil.equals(iFail, other.iFail) &&
			TarsUtil.equals(iChapterID, other.iChapterID) &&
			TarsUtil.equals(iSectionID, other.iSectionID) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(iRound, 0);
		_os.write(iWin, 1);
		_os.write(iFail, 2);
		_os.write(iChapterID, 3);
		_os.write(iSectionID, 4);
	}


	public void readFrom(TarsInputStream _is) {
		this.iRound = _is.read(iRound, 0, false);
		this.iWin = _is.read(iWin, 1, false);
		this.iFail = _is.read(iFail, 2, false);
		this.iChapterID = _is.read(iChapterID, 3, false);
		this.iSectionID = _is.read(iSectionID, 4, false);
	}

}
