// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.yoooum;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TItemInfo {

	@TarsStructProperty(order = 0, isRequire = false)
	public int iItemId = 0;
	@TarsStructProperty(order = 1, isRequire = false)
	public int iItemCount = 0;
	@TarsStructProperty(order = 2, isRequire = false)
	public int iItemType = 0;
	@TarsStructProperty(order = 3, isRequire = false)
	public int iExpiredTime = 0;

	public int getIItemId() {
		return iItemId;
	}

	public void setIItemId(int iItemId) {
		this.iItemId = iItemId;
	}

	public int getIItemCount() {
		return iItemCount;
	}

	public void setIItemCount(int iItemCount) {
		this.iItemCount = iItemCount;
	}

	public int getIItemType() {
		return iItemType;
	}

	public void setIItemType(int iItemType) {
		this.iItemType = iItemType;
	}

	public int getIExpiredTime() {
		return iExpiredTime;
	}

	public void setIExpiredTime(int iExpiredTime) {
		this.iExpiredTime = iExpiredTime;
	}

	public TItemInfo() {
	}

	public TItemInfo(int iItemId, int iItemCount, int iItemType, int iExpiredTime) {
		this.iItemId = iItemId;
		this.iItemCount = iItemCount;
		this.iItemType = iItemType;
		this.iExpiredTime = iExpiredTime;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(iItemId);
		result = prime * result + TarsUtil.hashCode(iItemCount);
		result = prime * result + TarsUtil.hashCode(iItemType);
		result = prime * result + TarsUtil.hashCode(iExpiredTime);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TItemInfo)) {
			return false;
		}
		TItemInfo other = (TItemInfo) obj;
		return (
			TarsUtil.equals(iItemId, other.iItemId) &&
			TarsUtil.equals(iItemCount, other.iItemCount) &&
			TarsUtil.equals(iItemType, other.iItemType) &&
			TarsUtil.equals(iExpiredTime, other.iExpiredTime) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(iItemId, 0);
		_os.write(iItemCount, 1);
		_os.write(iItemType, 2);
		_os.write(iExpiredTime, 3);
	}


	public void readFrom(TarsInputStream _is) {
		this.iItemId = _is.read(iItemId, 0, false);
		this.iItemCount = _is.read(iItemCount, 1, false);
		this.iItemType = _is.read(iItemType, 2, false);
		this.iExpiredTime = _is.read(iExpiredTime, 3, false);
	}

}
