// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.yoooum;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TItemListParam {

	@TarsStructProperty(order = 0, isRequire = false)
	public java.util.List<TItemParam> vItemList = null;

	public java.util.List<TItemParam> getVItemList() {
		return vItemList;
	}

	public void setVItemList(java.util.List<TItemParam> vItemList) {
		this.vItemList = vItemList;
	}

	public TItemListParam() {
	}

	public TItemListParam(java.util.List<TItemParam> vItemList) {
		this.vItemList = vItemList;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(vItemList);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TItemListParam)) {
			return false;
		}
		TItemListParam other = (TItemListParam) obj;
		return (
			TarsUtil.equals(vItemList, other.vItemList) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		if (null != vItemList) {
			_os.write(vItemList, 0);
		}
	}

	static java.util.List<TItemParam> cache_vItemList;
	static { 
		cache_vItemList = new java.util.ArrayList<TItemParam>();
		TItemParam var_59 = new TItemParam();
		cache_vItemList.add(var_59);
	}

	public void readFrom(TarsInputStream _is) {
		this.vItemList = (java.util.List<TItemParam>) _is.read(cache_vItemList, 0, false);
	}

}
