// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.yoooum;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TMailData {

	@TarsStructProperty(order = 0, isRequire = false)
	public int iMailId = 0;
	@TarsStructProperty(order = 1, isRequire = false)
	public int iMailType = 0;
	@TarsStructProperty(order = 2, isRequire = false)
	public int iStatus = 0;
	@TarsStructProperty(order = 3, isRequire = false)
	public String sTitle = "";
	@TarsStructProperty(order = 4, isRequire = false)
	public String sContent = "";
	@TarsStructProperty(order = 5, isRequire = false)
	public java.util.List<TItemInfo> vecAccessoryData = null;
	@TarsStructProperty(order = 6, isRequire = false)
	public int iExpireTime = 0;
	@TarsStructProperty(order = 7, isRequire = false)
	public int iSendTime = 0;
	@TarsStructProperty(order = 8, isRequire = false)
	public String sSender = "";

	public int getIMailId() {
		return iMailId;
	}

	public void setIMailId(int iMailId) {
		this.iMailId = iMailId;
	}

	public int getIMailType() {
		return iMailType;
	}

	public void setIMailType(int iMailType) {
		this.iMailType = iMailType;
	}

	public int getIStatus() {
		return iStatus;
	}

	public void setIStatus(int iStatus) {
		this.iStatus = iStatus;
	}

	public String getSTitle() {
		return sTitle;
	}

	public void setSTitle(String sTitle) {
		this.sTitle = sTitle;
	}

	public String getSContent() {
		return sContent;
	}

	public void setSContent(String sContent) {
		this.sContent = sContent;
	}

	public java.util.List<TItemInfo> getVecAccessoryData() {
		return vecAccessoryData;
	}

	public void setVecAccessoryData(java.util.List<TItemInfo> vecAccessoryData) {
		this.vecAccessoryData = vecAccessoryData;
	}

	public int getIExpireTime() {
		return iExpireTime;
	}

	public void setIExpireTime(int iExpireTime) {
		this.iExpireTime = iExpireTime;
	}

	public int getISendTime() {
		return iSendTime;
	}

	public void setISendTime(int iSendTime) {
		this.iSendTime = iSendTime;
	}

	public String getSSender() {
		return sSender;
	}

	public void setSSender(String sSender) {
		this.sSender = sSender;
	}

	public TMailData() {
	}

	public TMailData(int iMailId, int iMailType, int iStatus, String sTitle, String sContent, java.util.List<TItemInfo> vecAccessoryData, int iExpireTime, int iSendTime, String sSender) {
		this.iMailId = iMailId;
		this.iMailType = iMailType;
		this.iStatus = iStatus;
		this.sTitle = sTitle;
		this.sContent = sContent;
		this.vecAccessoryData = vecAccessoryData;
		this.iExpireTime = iExpireTime;
		this.iSendTime = iSendTime;
		this.sSender = sSender;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(iMailId);
		result = prime * result + TarsUtil.hashCode(iMailType);
		result = prime * result + TarsUtil.hashCode(iStatus);
		result = prime * result + TarsUtil.hashCode(sTitle);
		result = prime * result + TarsUtil.hashCode(sContent);
		result = prime * result + TarsUtil.hashCode(vecAccessoryData);
		result = prime * result + TarsUtil.hashCode(iExpireTime);
		result = prime * result + TarsUtil.hashCode(iSendTime);
		result = prime * result + TarsUtil.hashCode(sSender);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TMailData)) {
			return false;
		}
		TMailData other = (TMailData) obj;
		return (
			TarsUtil.equals(iMailId, other.iMailId) &&
			TarsUtil.equals(iMailType, other.iMailType) &&
			TarsUtil.equals(iStatus, other.iStatus) &&
			TarsUtil.equals(sTitle, other.sTitle) &&
			TarsUtil.equals(sContent, other.sContent) &&
			TarsUtil.equals(vecAccessoryData, other.vecAccessoryData) &&
			TarsUtil.equals(iExpireTime, other.iExpireTime) &&
			TarsUtil.equals(iSendTime, other.iSendTime) &&
			TarsUtil.equals(sSender, other.sSender) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(iMailId, 0);
		_os.write(iMailType, 1);
		_os.write(iStatus, 2);
		if (null != sTitle) {
			_os.write(sTitle, 3);
		}
		if (null != sContent) {
			_os.write(sContent, 4);
		}
		if (null != vecAccessoryData) {
			_os.write(vecAccessoryData, 5);
		}
		_os.write(iExpireTime, 6);
		_os.write(iSendTime, 7);
		if (null != sSender) {
			_os.write(sSender, 8);
		}
	}

	static java.util.List<TItemInfo> cache_vecAccessoryData;
	static { 
		cache_vecAccessoryData = new java.util.ArrayList<TItemInfo>();
		TItemInfo var_77 = new TItemInfo();
		cache_vecAccessoryData.add(var_77);
	}

	public void readFrom(TarsInputStream _is) {
		this.iMailId = _is.read(iMailId, 0, false);
		this.iMailType = _is.read(iMailType, 1, false);
		this.iStatus = _is.read(iStatus, 2, false);
		this.sTitle = _is.readString(3, false);
		this.sContent = _is.readString(4, false);
		this.vecAccessoryData = (java.util.List<TItemInfo>) _is.read(cache_vecAccessoryData, 5, false);
		this.iExpireTime = _is.read(iExpireTime, 6, false);
		this.iSendTime = _is.read(iSendTime, 7, false);
		this.sSender = _is.readString(8, false);
	}

}
