// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.yoooum;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TMemberInfo {

	@TarsStructProperty(order = 0, isRequire = false)
	public long uUin = 0L;
	@TarsStructProperty(order = 1, isRequire = false)
	public java.util.List<TUserTaskInfo> vecTaskData = null;
	@TarsStructProperty(order = 2, isRequire = false)
	public java.util.List<TBaseNpcInfo> vNPCInfo = null;
	@TarsStructProperty(order = 3, isRequire = false)
	public java.util.List<TGameData> aGameData = null;
	@TarsStructProperty(order = 4, isRequire = false)
	public TPlayerBagInfo stBagInfo = null;

	public long getUUin() {
		return uUin;
	}

	public void setUUin(long uUin) {
		this.uUin = uUin;
	}

	public java.util.List<TUserTaskInfo> getVecTaskData() {
		return vecTaskData;
	}

	public void setVecTaskData(java.util.List<TUserTaskInfo> vecTaskData) {
		this.vecTaskData = vecTaskData;
	}

	public java.util.List<TBaseNpcInfo> getVNPCInfo() {
		return vNPCInfo;
	}

	public void setVNPCInfo(java.util.List<TBaseNpcInfo> vNPCInfo) {
		this.vNPCInfo = vNPCInfo;
	}

	public java.util.List<TGameData> getAGameData() {
		return aGameData;
	}

	public void setAGameData(java.util.List<TGameData> aGameData) {
		this.aGameData = aGameData;
	}

	public TPlayerBagInfo getStBagInfo() {
		return stBagInfo;
	}

	public void setStBagInfo(TPlayerBagInfo stBagInfo) {
		this.stBagInfo = stBagInfo;
	}

	public TMemberInfo() {
	}

	public TMemberInfo(long uUin, java.util.List<TUserTaskInfo> vecTaskData, java.util.List<TBaseNpcInfo> vNPCInfo, java.util.List<TGameData> aGameData, TPlayerBagInfo stBagInfo) {
		this.uUin = uUin;
		this.vecTaskData = vecTaskData;
		this.vNPCInfo = vNPCInfo;
		this.aGameData = aGameData;
		this.stBagInfo = stBagInfo;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(uUin);
		result = prime * result + TarsUtil.hashCode(vecTaskData);
		result = prime * result + TarsUtil.hashCode(vNPCInfo);
		result = prime * result + TarsUtil.hashCode(aGameData);
		result = prime * result + TarsUtil.hashCode(stBagInfo);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TMemberInfo)) {
			return false;
		}
		TMemberInfo other = (TMemberInfo) obj;
		return (
			TarsUtil.equals(uUin, other.uUin) &&
			TarsUtil.equals(vecTaskData, other.vecTaskData) &&
			TarsUtil.equals(vNPCInfo, other.vNPCInfo) &&
			TarsUtil.equals(aGameData, other.aGameData) &&
			TarsUtil.equals(stBagInfo, other.stBagInfo) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(uUin, 0);
		if (null != vecTaskData) {
			_os.write(vecTaskData, 1);
		}
		if (null != vNPCInfo) {
			_os.write(vNPCInfo, 2);
		}
		if (null != aGameData) {
			_os.write(aGameData, 3);
		}
		if (null != stBagInfo) {
			_os.write(stBagInfo, 4);
		}
	}

	static java.util.List<TUserTaskInfo> cache_vecTaskData;
	static { 
		cache_vecTaskData = new java.util.ArrayList<TUserTaskInfo>();
		TUserTaskInfo var_74 = new TUserTaskInfo();
		cache_vecTaskData.add(var_74);
	}
	static java.util.List<TBaseNpcInfo> cache_vNPCInfo;
	static { 
		cache_vNPCInfo = new java.util.ArrayList<TBaseNpcInfo>();
		TBaseNpcInfo var_75 = new TBaseNpcInfo();
		cache_vNPCInfo.add(var_75);
	}
	static java.util.List<TGameData> cache_aGameData;
	static { 
		cache_aGameData = new java.util.ArrayList<TGameData>();
		TGameData var_76 = new TGameData();
		cache_aGameData.add(var_76);
	}
	static TPlayerBagInfo cache_stBagInfo;
	static { 
		cache_stBagInfo = new TPlayerBagInfo();
	}

	public void readFrom(TarsInputStream _is) {
		this.uUin = _is.read(uUin, 0, false);
		this.vecTaskData = (java.util.List<TUserTaskInfo>) _is.read(cache_vecTaskData, 1, false);
		this.vNPCInfo = (java.util.List<TBaseNpcInfo>) _is.read(cache_vNPCInfo, 2, false);
		this.aGameData = (java.util.List<TGameData>) _is.read(cache_aGameData, 3, false);
		this.stBagInfo = (TPlayerBagInfo) _is.read(cache_stBagInfo, 4, false);
	}

}
