// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.yoooum;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TMemberTaskInfo {

	@TarsStructProperty(order = 0, isRequire = false)
	public long uUin = 0L;
	@TarsStructProperty(order = 1, isRequire = false)
	public java.util.List<TUserTaskInfo> vecTaskData = null;

	public long getUUin() {
		return uUin;
	}

	public void setUUin(long uUin) {
		this.uUin = uUin;
	}

	public java.util.List<TUserTaskInfo> getVecTaskData() {
		return vecTaskData;
	}

	public void setVecTaskData(java.util.List<TUserTaskInfo> vecTaskData) {
		this.vecTaskData = vecTaskData;
	}

	public TMemberTaskInfo() {
	}

	public TMemberTaskInfo(long uUin, java.util.List<TUserTaskInfo> vecTaskData) {
		this.uUin = uUin;
		this.vecTaskData = vecTaskData;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(uUin);
		result = prime * result + TarsUtil.hashCode(vecTaskData);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TMemberTaskInfo)) {
			return false;
		}
		TMemberTaskInfo other = (TMemberTaskInfo) obj;
		return (
			TarsUtil.equals(uUin, other.uUin) &&
			TarsUtil.equals(vecTaskData, other.vecTaskData) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(uUin, 0);
		if (null != vecTaskData) {
			_os.write(vecTaskData, 1);
		}
	}

	static java.util.List<TUserTaskInfo> cache_vecTaskData;
	static { 
		cache_vecTaskData = new java.util.ArrayList<TUserTaskInfo>();
		TUserTaskInfo var_72 = new TUserTaskInfo();
		cache_vecTaskData.add(var_72);
	}

	public void readFrom(TarsInputStream _is) {
		this.uUin = _is.read(uUin, 0, false);
		this.vecTaskData = (java.util.List<TUserTaskInfo>) _is.read(cache_vecTaskData, 1, false);
	}

}
