// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.yoooum;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TMobilePhoneInfo {

	@TarsStructProperty(order = 0, isRequire = false)
	public String sOSType = "";
	@TarsStructProperty(order = 1, isRequire = false)
	public String sOSVersion = "";
	@TarsStructProperty(order = 2, isRequire = false)
	public String sPhoneMode = "";
	@TarsStructProperty(order = 3, isRequire = false)
	public String sTeleComOper = "";
	@TarsStructProperty(order = 4, isRequire = false)
	public int eNetworkType = 0;
	@TarsStructProperty(order = 5, isRequire = false)
	public int iScreenHight = 0;
	@TarsStructProperty(order = 6, isRequire = false)
	public int iScreenWidth = 0;
	@TarsStructProperty(order = 7, isRequire = false)
	public int iScreenDensity = 0;
	@TarsStructProperty(order = 8, isRequire = false)
	public String sCpuHardware = "";
	@TarsStructProperty(order = 9, isRequire = false)
	public int iMemory = 0;
	@TarsStructProperty(order = 10, isRequire = false)
	public String sMacAddr = "";
	@TarsStructProperty(order = 11, isRequire = false)
	public String sIMEI = "";
	@TarsStructProperty(order = 12, isRequire = false)
	public int eDeviceQuality = 0;
	@TarsStructProperty(order = 13, isRequire = false)
	public String sIDFA = "";
	@TarsStructProperty(order = 14, isRequire = false)
	public String sIDFV = "";
	@TarsStructProperty(order = 15, isRequire = false)
	public String sAndroidID = "";

	public String getSOSType() {
		return sOSType;
	}

	public void setSOSType(String sOSType) {
		this.sOSType = sOSType;
	}

	public String getSOSVersion() {
		return sOSVersion;
	}

	public void setSOSVersion(String sOSVersion) {
		this.sOSVersion = sOSVersion;
	}

	public String getSPhoneMode() {
		return sPhoneMode;
	}

	public void setSPhoneMode(String sPhoneMode) {
		this.sPhoneMode = sPhoneMode;
	}

	public String getSTeleComOper() {
		return sTeleComOper;
	}

	public void setSTeleComOper(String sTeleComOper) {
		this.sTeleComOper = sTeleComOper;
	}

	public int getENetworkType() {
		return eNetworkType;
	}

	public void setENetworkType(int eNetworkType) {
		this.eNetworkType = eNetworkType;
	}

	public int getIScreenHight() {
		return iScreenHight;
	}

	public void setIScreenHight(int iScreenHight) {
		this.iScreenHight = iScreenHight;
	}

	public int getIScreenWidth() {
		return iScreenWidth;
	}

	public void setIScreenWidth(int iScreenWidth) {
		this.iScreenWidth = iScreenWidth;
	}

	public int getIScreenDensity() {
		return iScreenDensity;
	}

	public void setIScreenDensity(int iScreenDensity) {
		this.iScreenDensity = iScreenDensity;
	}

	public String getSCpuHardware() {
		return sCpuHardware;
	}

	public void setSCpuHardware(String sCpuHardware) {
		this.sCpuHardware = sCpuHardware;
	}

	public int getIMemory() {
		return iMemory;
	}

	public void setIMemory(int iMemory) {
		this.iMemory = iMemory;
	}

	public String getSMacAddr() {
		return sMacAddr;
	}

	public void setSMacAddr(String sMacAddr) {
		this.sMacAddr = sMacAddr;
	}

	public String getSIMEI() {
		return sIMEI;
	}

	public void setSIMEI(String sIMEI) {
		this.sIMEI = sIMEI;
	}

	public int getEDeviceQuality() {
		return eDeviceQuality;
	}

	public void setEDeviceQuality(int eDeviceQuality) {
		this.eDeviceQuality = eDeviceQuality;
	}

	public String getSIDFA() {
		return sIDFA;
	}

	public void setSIDFA(String sIDFA) {
		this.sIDFA = sIDFA;
	}

	public String getSIDFV() {
		return sIDFV;
	}

	public void setSIDFV(String sIDFV) {
		this.sIDFV = sIDFV;
	}

	public String getSAndroidID() {
		return sAndroidID;
	}

	public void setSAndroidID(String sAndroidID) {
		this.sAndroidID = sAndroidID;
	}

	public TMobilePhoneInfo() {
	}

	public TMobilePhoneInfo(String sOSType, String sOSVersion, String sPhoneMode, String sTeleComOper, int eNetworkType, int iScreenHight, int iScreenWidth, int iScreenDensity, String sCpuHardware, int iMemory, String sMacAddr, String sIMEI, int eDeviceQuality, String sIDFA, String sIDFV, String sAndroidID) {
		this.sOSType = sOSType;
		this.sOSVersion = sOSVersion;
		this.sPhoneMode = sPhoneMode;
		this.sTeleComOper = sTeleComOper;
		this.eNetworkType = eNetworkType;
		this.iScreenHight = iScreenHight;
		this.iScreenWidth = iScreenWidth;
		this.iScreenDensity = iScreenDensity;
		this.sCpuHardware = sCpuHardware;
		this.iMemory = iMemory;
		this.sMacAddr = sMacAddr;
		this.sIMEI = sIMEI;
		this.eDeviceQuality = eDeviceQuality;
		this.sIDFA = sIDFA;
		this.sIDFV = sIDFV;
		this.sAndroidID = sAndroidID;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(sOSType);
		result = prime * result + TarsUtil.hashCode(sOSVersion);
		result = prime * result + TarsUtil.hashCode(sPhoneMode);
		result = prime * result + TarsUtil.hashCode(sTeleComOper);
		result = prime * result + TarsUtil.hashCode(eNetworkType);
		result = prime * result + TarsUtil.hashCode(iScreenHight);
		result = prime * result + TarsUtil.hashCode(iScreenWidth);
		result = prime * result + TarsUtil.hashCode(iScreenDensity);
		result = prime * result + TarsUtil.hashCode(sCpuHardware);
		result = prime * result + TarsUtil.hashCode(iMemory);
		result = prime * result + TarsUtil.hashCode(sMacAddr);
		result = prime * result + TarsUtil.hashCode(sIMEI);
		result = prime * result + TarsUtil.hashCode(eDeviceQuality);
		result = prime * result + TarsUtil.hashCode(sIDFA);
		result = prime * result + TarsUtil.hashCode(sIDFV);
		result = prime * result + TarsUtil.hashCode(sAndroidID);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TMobilePhoneInfo)) {
			return false;
		}
		TMobilePhoneInfo other = (TMobilePhoneInfo) obj;
		return (
			TarsUtil.equals(sOSType, other.sOSType) &&
			TarsUtil.equals(sOSVersion, other.sOSVersion) &&
			TarsUtil.equals(sPhoneMode, other.sPhoneMode) &&
			TarsUtil.equals(sTeleComOper, other.sTeleComOper) &&
			TarsUtil.equals(eNetworkType, other.eNetworkType) &&
			TarsUtil.equals(iScreenHight, other.iScreenHight) &&
			TarsUtil.equals(iScreenWidth, other.iScreenWidth) &&
			TarsUtil.equals(iScreenDensity, other.iScreenDensity) &&
			TarsUtil.equals(sCpuHardware, other.sCpuHardware) &&
			TarsUtil.equals(iMemory, other.iMemory) &&
			TarsUtil.equals(sMacAddr, other.sMacAddr) &&
			TarsUtil.equals(sIMEI, other.sIMEI) &&
			TarsUtil.equals(eDeviceQuality, other.eDeviceQuality) &&
			TarsUtil.equals(sIDFA, other.sIDFA) &&
			TarsUtil.equals(sIDFV, other.sIDFV) &&
			TarsUtil.equals(sAndroidID, other.sAndroidID) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		if (null != sOSType) {
			_os.write(sOSType, 0);
		}
		if (null != sOSVersion) {
			_os.write(sOSVersion, 1);
		}
		if (null != sPhoneMode) {
			_os.write(sPhoneMode, 2);
		}
		if (null != sTeleComOper) {
			_os.write(sTeleComOper, 3);
		}
		_os.write(eNetworkType, 4);
		_os.write(iScreenHight, 5);
		_os.write(iScreenWidth, 6);
		_os.write(iScreenDensity, 7);
		if (null != sCpuHardware) {
			_os.write(sCpuHardware, 8);
		}
		_os.write(iMemory, 9);
		if (null != sMacAddr) {
			_os.write(sMacAddr, 10);
		}
		if (null != sIMEI) {
			_os.write(sIMEI, 11);
		}
		_os.write(eDeviceQuality, 12);
		if (null != sIDFA) {
			_os.write(sIDFA, 13);
		}
		if (null != sIDFV) {
			_os.write(sIDFV, 14);
		}
		if (null != sAndroidID) {
			_os.write(sAndroidID, 15);
		}
	}


	public void readFrom(TarsInputStream _is) {
		this.sOSType = _is.readString(0, false);
		this.sOSVersion = _is.readString(1, false);
		this.sPhoneMode = _is.readString(2, false);
		this.sTeleComOper = _is.readString(3, false);
		this.eNetworkType = _is.read(eNetworkType, 4, false);
		this.iScreenHight = _is.read(iScreenHight, 5, false);
		this.iScreenWidth = _is.read(iScreenWidth, 6, false);
		this.iScreenDensity = _is.read(iScreenDensity, 7, false);
		this.sCpuHardware = _is.readString(8, false);
		this.iMemory = _is.read(iMemory, 9, false);
		this.sMacAddr = _is.readString(10, false);
		this.sIMEI = _is.readString(11, false);
		this.eDeviceQuality = _is.read(eDeviceQuality, 12, false);
		this.sIDFA = _is.readString(13, false);
		this.sIDFV = _is.readString(14, false);
		this.sAndroidID = _is.readString(15, false);
	}

}
