// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.yoooum;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TMultipleAwardTypeCfg {

	@TarsStructProperty(order = 0, isRequire = false)
	public int iAwardId = 0;
	@TarsStructProperty(order = 1, isRequire = false)
	public String sAwardDesc = "";
	@TarsStructProperty(order = 2, isRequire = false)
	public int iAwardType = 0;
	@TarsStructProperty(order = 3, isRequire = false)
	public int iItemId = 0;
	@TarsStructProperty(order = 4, isRequire = false)
	public int iItemNum = 0;
	@TarsStructProperty(order = 5, isRequire = false)
	public int iCalcRate = 0;

	public int getIAwardId() {
		return iAwardId;
	}

	public void setIAwardId(int iAwardId) {
		this.iAwardId = iAwardId;
	}

	public String getSAwardDesc() {
		return sAwardDesc;
	}

	public void setSAwardDesc(String sAwardDesc) {
		this.sAwardDesc = sAwardDesc;
	}

	public int getIAwardType() {
		return iAwardType;
	}

	public void setIAwardType(int iAwardType) {
		this.iAwardType = iAwardType;
	}

	public int getIItemId() {
		return iItemId;
	}

	public void setIItemId(int iItemId) {
		this.iItemId = iItemId;
	}

	public int getIItemNum() {
		return iItemNum;
	}

	public void setIItemNum(int iItemNum) {
		this.iItemNum = iItemNum;
	}

	public int getICalcRate() {
		return iCalcRate;
	}

	public void setICalcRate(int iCalcRate) {
		this.iCalcRate = iCalcRate;
	}

	public TMultipleAwardTypeCfg() {
	}

	public TMultipleAwardTypeCfg(int iAwardId, String sAwardDesc, int iAwardType, int iItemId, int iItemNum, int iCalcRate) {
		this.iAwardId = iAwardId;
		this.sAwardDesc = sAwardDesc;
		this.iAwardType = iAwardType;
		this.iItemId = iItemId;
		this.iItemNum = iItemNum;
		this.iCalcRate = iCalcRate;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(iAwardId);
		result = prime * result + TarsUtil.hashCode(sAwardDesc);
		result = prime * result + TarsUtil.hashCode(iAwardType);
		result = prime * result + TarsUtil.hashCode(iItemId);
		result = prime * result + TarsUtil.hashCode(iItemNum);
		result = prime * result + TarsUtil.hashCode(iCalcRate);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TMultipleAwardTypeCfg)) {
			return false;
		}
		TMultipleAwardTypeCfg other = (TMultipleAwardTypeCfg) obj;
		return (
			TarsUtil.equals(iAwardId, other.iAwardId) &&
			TarsUtil.equals(sAwardDesc, other.sAwardDesc) &&
			TarsUtil.equals(iAwardType, other.iAwardType) &&
			TarsUtil.equals(iItemId, other.iItemId) &&
			TarsUtil.equals(iItemNum, other.iItemNum) &&
			TarsUtil.equals(iCalcRate, other.iCalcRate) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(iAwardId, 0);
		if (null != sAwardDesc) {
			_os.write(sAwardDesc, 1);
		}
		_os.write(iAwardType, 2);
		_os.write(iItemId, 3);
		_os.write(iItemNum, 4);
		_os.write(iCalcRate, 5);
	}


	public void readFrom(TarsInputStream _is) {
		this.iAwardId = _is.read(iAwardId, 0, false);
		this.sAwardDesc = _is.readString(1, false);
		this.iAwardType = _is.read(iAwardType, 2, false);
		this.iItemId = _is.read(iItemId, 3, false);
		this.iItemNum = _is.read(iItemNum, 4, false);
		this.iCalcRate = _is.read(iCalcRate, 5, false);
	}

}
