// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.yoooum;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TPlayerBagInfo {

	@TarsStructProperty(order = 0, isRequire = false)
	public long uUin = 0L;
	@TarsStructProperty(order = 1, isRequire = false)
	public int iZoneID = 0;
	@TarsStructProperty(order = 2, isRequire = false)
	public java.util.List<TBagSlot> vBagList = null;
	@TarsStructProperty(order = 3, isRequire = false)
	public short usBagSize = (short)0;

	public long getUUin() {
		return uUin;
	}

	public void setUUin(long uUin) {
		this.uUin = uUin;
	}

	public int getIZoneID() {
		return iZoneID;
	}

	public void setIZoneID(int iZoneID) {
		this.iZoneID = iZoneID;
	}

	public java.util.List<TBagSlot> getVBagList() {
		return vBagList;
	}

	public void setVBagList(java.util.List<TBagSlot> vBagList) {
		this.vBagList = vBagList;
	}

	public short getUsBagSize() {
		return usBagSize;
	}

	public void setUsBagSize(short usBagSize) {
		this.usBagSize = usBagSize;
	}

	public TPlayerBagInfo() {
	}

	public TPlayerBagInfo(long uUin, int iZoneID, java.util.List<TBagSlot> vBagList, short usBagSize) {
		this.uUin = uUin;
		this.iZoneID = iZoneID;
		this.vBagList = vBagList;
		this.usBagSize = usBagSize;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(uUin);
		result = prime * result + TarsUtil.hashCode(iZoneID);
		result = prime * result + TarsUtil.hashCode(vBagList);
		result = prime * result + TarsUtil.hashCode(usBagSize);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TPlayerBagInfo)) {
			return false;
		}
		TPlayerBagInfo other = (TPlayerBagInfo) obj;
		return (
			TarsUtil.equals(uUin, other.uUin) &&
			TarsUtil.equals(iZoneID, other.iZoneID) &&
			TarsUtil.equals(vBagList, other.vBagList) &&
			TarsUtil.equals(usBagSize, other.usBagSize) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(uUin, 0);
		_os.write(iZoneID, 1);
		if (null != vBagList) {
			_os.write(vBagList, 2);
		}
		_os.write(usBagSize, 3);
	}

	static java.util.List<TBagSlot> cache_vBagList;
	static { 
		cache_vBagList = new java.util.ArrayList<TBagSlot>();
		TBagSlot var_62 = new TBagSlot();
		cache_vBagList.add(var_62);
	}

	public void readFrom(TarsInputStream _is) {
		this.uUin = _is.read(uUin, 0, false);
		this.iZoneID = _is.read(iZoneID, 1, false);
		this.vBagList = (java.util.List<TBagSlot>) _is.read(cache_vBagList, 2, false);
		this.usBagSize = _is.read(usBagSize, 3, false);
	}

}
