// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.yoooum;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TR2RSPackage {

	@TarsStructProperty(order = 0, isRequire = true)
	public TRouterHead stRouterHead = null;
	@TarsStructProperty(order = 1, isRequire = true)
	public TRSPackage stRSPkg = null;

	public TRouterHead getStRouterHead() {
		return stRouterHead;
	}

	public void setStRouterHead(TRouterHead stRouterHead) {
		this.stRouterHead = stRouterHead;
	}

	public TRSPackage getStRSPkg() {
		return stRSPkg;
	}

	public void setStRSPkg(TRSPackage stRSPkg) {
		this.stRSPkg = stRSPkg;
	}

	public TR2RSPackage() {
	}

	public TR2RSPackage(TRouterHead stRouterHead, TRSPackage stRSPkg) {
		this.stRouterHead = stRouterHead;
		this.stRSPkg = stRSPkg;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(stRouterHead);
		result = prime * result + TarsUtil.hashCode(stRSPkg);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TR2RSPackage)) {
			return false;
		}
		TR2RSPackage other = (TR2RSPackage) obj;
		return (
			TarsUtil.equals(stRouterHead, other.stRouterHead) &&
			TarsUtil.equals(stRSPkg, other.stRSPkg) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(stRouterHead, 0);
		_os.write(stRSPkg, 1);
	}

	static TRouterHead cache_stRouterHead;
	static { 
		cache_stRouterHead = new TRouterHead();
	}
	static TRSPackage cache_stRSPkg;
	static { 
		cache_stRSPkg = new TRSPackage();
	}

	public void readFrom(TarsInputStream _is) {
		this.stRouterHead = (TRouterHead) _is.read(cache_stRouterHead, 0, true);
		this.stRSPkg = (TRSPackage) _is.read(cache_stRSPkg, 1, true);
	}

}
