// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.yoooum;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TRouterHead {

	@TarsStructProperty(order = 0, isRequire = true)
	public String sClientIP = "";
	@TarsStructProperty(order = 1, isRequire = true)
	public int iClientPort = 0;
	@TarsStructProperty(order = 2, isRequire = true)
	public long iConnID = 0L;
	@TarsStructProperty(order = 3, isRequire = true)
	public String sRouterObj = "";
	@TarsStructProperty(order = 4, isRequire = true)
	public String sRealSvrObj = "";
	@TarsStructProperty(order = 5, isRequire = false)
	public String sZoneSvrObj = "";

	public String getSClientIP() {
		return sClientIP;
	}

	public void setSClientIP(String sClientIP) {
		this.sClientIP = sClientIP;
	}

	public int getIClientPort() {
		return iClientPort;
	}

	public void setIClientPort(int iClientPort) {
		this.iClientPort = iClientPort;
	}

	public long getIConnID() {
		return iConnID;
	}

	public void setIConnID(long iConnID) {
		this.iConnID = iConnID;
	}

	public String getSRouterObj() {
		return sRouterObj;
	}

	public void setSRouterObj(String sRouterObj) {
		this.sRouterObj = sRouterObj;
	}

	public String getSRealSvrObj() {
		return sRealSvrObj;
	}

	public void setSRealSvrObj(String sRealSvrObj) {
		this.sRealSvrObj = sRealSvrObj;
	}

	public String getSZoneSvrObj() {
		return sZoneSvrObj;
	}

	public void setSZoneSvrObj(String sZoneSvrObj) {
		this.sZoneSvrObj = sZoneSvrObj;
	}

	public TRouterHead() {
	}

	public TRouterHead(String sClientIP, int iClientPort, long iConnID, String sRouterObj, String sRealSvrObj, String sZoneSvrObj) {
		this.sClientIP = sClientIP;
		this.iClientPort = iClientPort;
		this.iConnID = iConnID;
		this.sRouterObj = sRouterObj;
		this.sRealSvrObj = sRealSvrObj;
		this.sZoneSvrObj = sZoneSvrObj;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(sClientIP);
		result = prime * result + TarsUtil.hashCode(iClientPort);
		result = prime * result + TarsUtil.hashCode(iConnID);
		result = prime * result + TarsUtil.hashCode(sRouterObj);
		result = prime * result + TarsUtil.hashCode(sRealSvrObj);
		result = prime * result + TarsUtil.hashCode(sZoneSvrObj);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TRouterHead)) {
			return false;
		}
		TRouterHead other = (TRouterHead) obj;
		return (
			TarsUtil.equals(sClientIP, other.sClientIP) &&
			TarsUtil.equals(iClientPort, other.iClientPort) &&
			TarsUtil.equals(iConnID, other.iConnID) &&
			TarsUtil.equals(sRouterObj, other.sRouterObj) &&
			TarsUtil.equals(sRealSvrObj, other.sRealSvrObj) &&
			TarsUtil.equals(sZoneSvrObj, other.sZoneSvrObj) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(sClientIP, 0);
		_os.write(iClientPort, 1);
		_os.write(iConnID, 2);
		_os.write(sRouterObj, 3);
		_os.write(sRealSvrObj, 4);
		if (null != sZoneSvrObj) {
			_os.write(sZoneSvrObj, 5);
		}
	}


	public void readFrom(TarsInputStream _is) {
		this.sClientIP = _is.readString(0, true);
		this.iClientPort = _is.read(iClientPort, 1, true);
		this.iConnID = _is.read(iConnID, 2, true);
		this.sRouterObj = _is.readString(3, true);
		this.sRealSvrObj = _is.readString(4, true);
		this.sZoneSvrObj = _is.readString(5, false);
	}

}
