// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.yoooum;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TRPackage {

	@TarsStructProperty(order = 0, isRequire = true)
	public String sOpenID = "";
	@TarsStructProperty(order = 1, isRequire = true)
	public int iMsgID = 0;
	@TarsStructProperty(order = 2, isRequire = true)
	public int eMsgType = 0;
	@TarsStructProperty(order = 3, isRequire = true)
	public String sMsgBody = "";
	@TarsStructProperty(order = 4, isRequire = false)
	public int iZoneID = 0;

	public String getSOpenID() {
		return sOpenID;
	}

	public void setSOpenID(String sOpenID) {
		this.sOpenID = sOpenID;
	}

	public int getIMsgID() {
		return iMsgID;
	}

	public void setIMsgID(int iMsgID) {
		this.iMsgID = iMsgID;
	}

	public int getEMsgType() {
		return eMsgType;
	}

	public void setEMsgType(int eMsgType) {
		this.eMsgType = eMsgType;
	}

	public String getSMsgBody() {
		return sMsgBody;
	}

	public void setSMsgBody(String sMsgBody) {
		this.sMsgBody = sMsgBody;
	}

	public int getIZoneID() {
		return iZoneID;
	}

	public void setIZoneID(int iZoneID) {
		this.iZoneID = iZoneID;
	}

	public TRPackage() {
	}

	public TRPackage(String sOpenID, int iMsgID, int eMsgType, String sMsgBody, int iZoneID) {
		this.sOpenID = sOpenID;
		this.iMsgID = iMsgID;
		this.eMsgType = eMsgType;
		this.sMsgBody = sMsgBody;
		this.iZoneID = iZoneID;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(sOpenID);
		result = prime * result + TarsUtil.hashCode(iMsgID);
		result = prime * result + TarsUtil.hashCode(eMsgType);
		result = prime * result + TarsUtil.hashCode(sMsgBody);
		result = prime * result + TarsUtil.hashCode(iZoneID);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TRPackage)) {
			return false;
		}
		TRPackage other = (TRPackage) obj;
		return (
			TarsUtil.equals(sOpenID, other.sOpenID) &&
			TarsUtil.equals(iMsgID, other.iMsgID) &&
			TarsUtil.equals(eMsgType, other.eMsgType) &&
			TarsUtil.equals(sMsgBody, other.sMsgBody) &&
			TarsUtil.equals(iZoneID, other.iZoneID) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(sOpenID, 0);
		_os.write(iMsgID, 1);
		_os.write(eMsgType, 2);
		_os.write(sMsgBody, 3);
		_os.write(iZoneID, 4);
	}


	public void readFrom(TarsInputStream _is) {
		this.sOpenID = _is.readString(0, true);
		this.iMsgID = _is.read(iMsgID, 1, true);
		this.eMsgType = _is.read(eMsgType, 2, true);
		this.sMsgBody = _is.readString(3, true);
		this.iZoneID = _is.read(iZoneID, 4, false);
	}

}
