// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.yoooum;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TRSPackage {

	@TarsStructProperty(order = 0, isRequire = true)
	public int eOpenPlatType = 0;
	@TarsStructProperty(order = 1, isRequire = true)
	public String sOpenID = "";
	@TarsStructProperty(order = 2, isRequire = true)
	public long uUin = 0;
	@TarsStructProperty(order = 3, isRequire = false)
	public int iZoneID = 0;
	@TarsStructProperty(order = 4, isRequire = false)
	public int iClientVer = 0;
	@TarsStructProperty(order = 5, isRequire = true)
	public int iMsgID = 0;
	@TarsStructProperty(order = 6, isRequire = true)
	public int eMsgType = 0;
	@TarsStructProperty(order = 7, isRequire = true)
	public String sMsgBody = "";
	@TarsStructProperty(order = 8, isRequire = false)
	public int eLang = 0;

	public int getEOpenPlatType() {
		return eOpenPlatType;
	}

	public void setEOpenPlatType(int eOpenPlatType) {
		this.eOpenPlatType = eOpenPlatType;
	}

	public String getSOpenID() {
		return sOpenID;
	}

	public void setSOpenID(String sOpenID) {
		this.sOpenID = sOpenID;
	}

	public long getUUin() {
		return uUin;
	}

	public void setUUin(long uUin) {
		this.uUin = uUin;
	}

	public int getIZoneID() {
		return iZoneID;
	}

	public void setIZoneID(int iZoneID) {
		this.iZoneID = iZoneID;
	}

	public int getIClientVer() {
		return iClientVer;
	}

	public void setIClientVer(int iClientVer) {
		this.iClientVer = iClientVer;
	}

	public int getIMsgID() {
		return iMsgID;
	}

	public void setIMsgID(int iMsgID) {
		this.iMsgID = iMsgID;
	}

	public int getEMsgType() {
		return eMsgType;
	}

	public void setEMsgType(int eMsgType) {
		this.eMsgType = eMsgType;
	}

	public String getSMsgBody() {
		return sMsgBody;
	}

	public void setSMsgBody(String sMsgBody) {
		this.sMsgBody = sMsgBody;
	}

	public int getELang() {
		return eLang;
	}

	public void setELang(int eLang) {
		this.eLang = eLang;
	}

	public TRSPackage() {
	}

	public TRSPackage(int eOpenPlatType, String sOpenID, long uUin, int iZoneID, int iClientVer, int iMsgID, int eMsgType, String sMsgBody, int eLang) {
		this.eOpenPlatType = eOpenPlatType;
		this.sOpenID = sOpenID;
		this.uUin = uUin;
		this.iZoneID = iZoneID;
		this.iClientVer = iClientVer;
		this.iMsgID = iMsgID;
		this.eMsgType = eMsgType;
		this.sMsgBody = sMsgBody;
		this.eLang = eLang;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(eOpenPlatType);
		result = prime * result + TarsUtil.hashCode(sOpenID);
		result = prime * result + TarsUtil.hashCode(uUin);
		result = prime * result + TarsUtil.hashCode(iZoneID);
		result = prime * result + TarsUtil.hashCode(iClientVer);
		result = prime * result + TarsUtil.hashCode(iMsgID);
		result = prime * result + TarsUtil.hashCode(eMsgType);
		result = prime * result + TarsUtil.hashCode(sMsgBody);
		result = prime * result + TarsUtil.hashCode(eLang);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TRSPackage)) {
			return false;
		}
		TRSPackage other = (TRSPackage) obj;
		return (
			TarsUtil.equals(eOpenPlatType, other.eOpenPlatType) &&
			TarsUtil.equals(sOpenID, other.sOpenID) &&
			TarsUtil.equals(uUin, other.uUin) &&
			TarsUtil.equals(iZoneID, other.iZoneID) &&
			TarsUtil.equals(iClientVer, other.iClientVer) &&
			TarsUtil.equals(iMsgID, other.iMsgID) &&
			TarsUtil.equals(eMsgType, other.eMsgType) &&
			TarsUtil.equals(sMsgBody, other.sMsgBody) &&
			TarsUtil.equals(eLang, other.eLang) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(eOpenPlatType, 0);
		_os.write(sOpenID, 1);
		_os.write(uUin, 2);
		_os.write(iZoneID, 3);
		_os.write(iClientVer, 4);
		_os.write(iMsgID, 5);
		_os.write(eMsgType, 6);
		_os.write(sMsgBody, 7);
		_os.write(eLang, 8);
	}


	public void readFrom(TarsInputStream _is) {
		this.eOpenPlatType = _is.read(eOpenPlatType, 0, true);
		this.sOpenID = _is.readString(1, true);
		this.uUin = _is.read(uUin, 2, true);
		this.iZoneID = _is.read(iZoneID, 3, false);
		this.iClientVer = _is.read(iClientVer, 4, false);
		this.iMsgID = _is.read(iMsgID, 5, true);
		this.eMsgType = _is.read(eMsgType, 6, true);
		this.sMsgBody = _is.readString(7, true);
		this.eLang = _is.read(eLang, 8, false);
	}

}
