// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.yoooum;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TTaskCommonData {

	@TarsStructProperty(order = 0, isRequire = false)
	public int iTaskId = 0;
	@TarsStructProperty(order = 1, isRequire = false)
	public int iTarget = 0;
	@TarsStructProperty(order = 2, isRequire = false)
	public int iTargetProcess = 0;
	@TarsStructProperty(order = 3, isRequire = false)
	public int iState = 0;
	@TarsStructProperty(order = 4, isRequire = false)
	public int iDesireId = 0;

	public int getITaskId() {
		return iTaskId;
	}

	public void setITaskId(int iTaskId) {
		this.iTaskId = iTaskId;
	}

	public int getITarget() {
		return iTarget;
	}

	public void setITarget(int iTarget) {
		this.iTarget = iTarget;
	}

	public int getITargetProcess() {
		return iTargetProcess;
	}

	public void setITargetProcess(int iTargetProcess) {
		this.iTargetProcess = iTargetProcess;
	}

	public int getIState() {
		return iState;
	}

	public void setIState(int iState) {
		this.iState = iState;
	}

	public int getIDesireId() {
		return iDesireId;
	}

	public void setIDesireId(int iDesireId) {
		this.iDesireId = iDesireId;
	}

	public TTaskCommonData() {
	}

	public TTaskCommonData(int iTaskId, int iTarget, int iTargetProcess, int iState, int iDesireId) {
		this.iTaskId = iTaskId;
		this.iTarget = iTarget;
		this.iTargetProcess = iTargetProcess;
		this.iState = iState;
		this.iDesireId = iDesireId;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(iTaskId);
		result = prime * result + TarsUtil.hashCode(iTarget);
		result = prime * result + TarsUtil.hashCode(iTargetProcess);
		result = prime * result + TarsUtil.hashCode(iState);
		result = prime * result + TarsUtil.hashCode(iDesireId);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TTaskCommonData)) {
			return false;
		}
		TTaskCommonData other = (TTaskCommonData) obj;
		return (
			TarsUtil.equals(iTaskId, other.iTaskId) &&
			TarsUtil.equals(iTarget, other.iTarget) &&
			TarsUtil.equals(iTargetProcess, other.iTargetProcess) &&
			TarsUtil.equals(iState, other.iState) &&
			TarsUtil.equals(iDesireId, other.iDesireId) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(iTaskId, 0);
		_os.write(iTarget, 1);
		_os.write(iTargetProcess, 2);
		_os.write(iState, 3);
		_os.write(iDesireId, 4);
	}


	public void readFrom(TarsInputStream _is) {
		this.iTaskId = _is.read(iTaskId, 0, false);
		this.iTarget = _is.read(iTarget, 1, false);
		this.iTargetProcess = _is.read(iTargetProcess, 2, false);
		this.iState = _is.read(iState, 3, false);
		this.iDesireId = _is.read(iDesireId, 4, false);
	}

}
