// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.yoooum;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TTaskDesireCfg {

	@TarsStructProperty(order = 0, isRequire = false)
	public int iDesireId = 0;
	@TarsStructProperty(order = 1, isRequire = false)
	public String sDesireDesc = "";
	@TarsStructProperty(order = 2, isRequire = false)
	public int iDesireValue = 0;
	@TarsStructProperty(order = 3, isRequire = false)
	public int iItemId = 0;
	@TarsStructProperty(order = 4, isRequire = false)
	public String sJumpTo = "";
	@TarsStructProperty(order = 5, isRequire = false)
	public int iCommonId = 0;
	@TarsStructProperty(order = 6, isRequire = false)
	public java.util.List<TTaskContionCfg> vecCondition = null;
	@TarsStructProperty(order = 7, isRequire = false)
	public short nPriority = (short)0;

	public int getIDesireId() {
		return iDesireId;
	}

	public void setIDesireId(int iDesireId) {
		this.iDesireId = iDesireId;
	}

	public String getSDesireDesc() {
		return sDesireDesc;
	}

	public void setSDesireDesc(String sDesireDesc) {
		this.sDesireDesc = sDesireDesc;
	}

	public int getIDesireValue() {
		return iDesireValue;
	}

	public void setIDesireValue(int iDesireValue) {
		this.iDesireValue = iDesireValue;
	}

	public int getIItemId() {
		return iItemId;
	}

	public void setIItemId(int iItemId) {
		this.iItemId = iItemId;
	}

	public String getSJumpTo() {
		return sJumpTo;
	}

	public void setSJumpTo(String sJumpTo) {
		this.sJumpTo = sJumpTo;
	}

	public int getICommonId() {
		return iCommonId;
	}

	public void setICommonId(int iCommonId) {
		this.iCommonId = iCommonId;
	}

	public java.util.List<TTaskContionCfg> getVecCondition() {
		return vecCondition;
	}

	public void setVecCondition(java.util.List<TTaskContionCfg> vecCondition) {
		this.vecCondition = vecCondition;
	}

	public short getNPriority() {
		return nPriority;
	}

	public void setNPriority(short nPriority) {
		this.nPriority = nPriority;
	}

	public TTaskDesireCfg() {
	}

	public TTaskDesireCfg(int iDesireId, String sDesireDesc, int iDesireValue, int iItemId, String sJumpTo, int iCommonId, java.util.List<TTaskContionCfg> vecCondition, short nPriority) {
		this.iDesireId = iDesireId;
		this.sDesireDesc = sDesireDesc;
		this.iDesireValue = iDesireValue;
		this.iItemId = iItemId;
		this.sJumpTo = sJumpTo;
		this.iCommonId = iCommonId;
		this.vecCondition = vecCondition;
		this.nPriority = nPriority;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(iDesireId);
		result = prime * result + TarsUtil.hashCode(sDesireDesc);
		result = prime * result + TarsUtil.hashCode(iDesireValue);
		result = prime * result + TarsUtil.hashCode(iItemId);
		result = prime * result + TarsUtil.hashCode(sJumpTo);
		result = prime * result + TarsUtil.hashCode(iCommonId);
		result = prime * result + TarsUtil.hashCode(vecCondition);
		result = prime * result + TarsUtil.hashCode(nPriority);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TTaskDesireCfg)) {
			return false;
		}
		TTaskDesireCfg other = (TTaskDesireCfg) obj;
		return (
			TarsUtil.equals(iDesireId, other.iDesireId) &&
			TarsUtil.equals(sDesireDesc, other.sDesireDesc) &&
			TarsUtil.equals(iDesireValue, other.iDesireValue) &&
			TarsUtil.equals(iItemId, other.iItemId) &&
			TarsUtil.equals(sJumpTo, other.sJumpTo) &&
			TarsUtil.equals(iCommonId, other.iCommonId) &&
			TarsUtil.equals(vecCondition, other.vecCondition) &&
			TarsUtil.equals(nPriority, other.nPriority) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(iDesireId, 0);
		if (null != sDesireDesc) {
			_os.write(sDesireDesc, 1);
		}
		_os.write(iDesireValue, 2);
		_os.write(iItemId, 3);
		if (null != sJumpTo) {
			_os.write(sJumpTo, 4);
		}
		_os.write(iCommonId, 5);
		if (null != vecCondition) {
			_os.write(vecCondition, 6);
		}
		_os.write(nPriority, 7);
	}

	static java.util.List<TTaskContionCfg> cache_vecCondition;
	static { 
		cache_vecCondition = new java.util.ArrayList<TTaskContionCfg>();
		TTaskContionCfg var_64 = new TTaskContionCfg();
		cache_vecCondition.add(var_64);
	}

	public void readFrom(TarsInputStream _is) {
		this.iDesireId = _is.read(iDesireId, 0, false);
		this.sDesireDesc = _is.readString(1, false);
		this.iDesireValue = _is.read(iDesireValue, 2, false);
		this.iItemId = _is.read(iItemId, 3, false);
		this.sJumpTo = _is.readString(4, false);
		this.iCommonId = _is.read(iCommonId, 5, false);
		this.vecCondition = (java.util.List<TTaskContionCfg>) _is.read(cache_vecCondition, 6, false);
		this.nPriority = _is.read(nPriority, 7, false);
	}

}
