// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.yoooum;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TTokenInfo {

	@TarsStructProperty(order = 0, isRequire = false)
	public String sAccessToken = "";
	@TarsStructProperty(order = 1, isRequire = false)
	public String sPayToken = "";
	@TarsStructProperty(order = 2, isRequire = false)
	public String sPf = "";
	@TarsStructProperty(order = 4, isRequire = false)
	public String sPfKey = "";

	public String getSAccessToken() {
		return sAccessToken;
	}

	public void setSAccessToken(String sAccessToken) {
		this.sAccessToken = sAccessToken;
	}

	public String getSPayToken() {
		return sPayToken;
	}

	public void setSPayToken(String sPayToken) {
		this.sPayToken = sPayToken;
	}

	public String getSPf() {
		return sPf;
	}

	public void setSPf(String sPf) {
		this.sPf = sPf;
	}

	public String getSPfKey() {
		return sPfKey;
	}

	public void setSPfKey(String sPfKey) {
		this.sPfKey = sPfKey;
	}

	public TTokenInfo() {
	}

	public TTokenInfo(String sAccessToken, String sPayToken, String sPf, String sPfKey) {
		this.sAccessToken = sAccessToken;
		this.sPayToken = sPayToken;
		this.sPf = sPf;
		this.sPfKey = sPfKey;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(sAccessToken);
		result = prime * result + TarsUtil.hashCode(sPayToken);
		result = prime * result + TarsUtil.hashCode(sPf);
		result = prime * result + TarsUtil.hashCode(sPfKey);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TTokenInfo)) {
			return false;
		}
		TTokenInfo other = (TTokenInfo) obj;
		return (
			TarsUtil.equals(sAccessToken, other.sAccessToken) &&
			TarsUtil.equals(sPayToken, other.sPayToken) &&
			TarsUtil.equals(sPf, other.sPf) &&
			TarsUtil.equals(sPfKey, other.sPfKey) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		if (null != sAccessToken) {
			_os.write(sAccessToken, 0);
		}
		if (null != sPayToken) {
			_os.write(sPayToken, 1);
		}
		if (null != sPf) {
			_os.write(sPf, 2);
		}
		if (null != sPfKey) {
			_os.write(sPfKey, 4);
		}
	}


	public void readFrom(TarsInputStream _is) {
		this.sAccessToken = _is.readString(0, false);
		this.sPayToken = _is.readString(1, false);
		this.sPf = _is.readString(2, false);
		this.sPfKey = _is.readString(4, false);
	}

}
