// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.yoooum;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TUserZoneInfo {

	@TarsStructProperty(order = 0, isRequire = false)
	public int iZoneID = 0;
	@TarsStructProperty(order = 1, isRequire = false)
	public String sName = "";
	@TarsStructProperty(order = 2, isRequire = false)
	public int iSvrStatue = 0;
	@TarsStructProperty(order = 3, isRequire = false)
	public boolean bExistRole = false;
	@TarsStructProperty(order = 4, isRequire = false)
	public long lLastTM = 0L;
	@TarsStructProperty(order = 5, isRequire = false)
	public short nRoleStatus = (short)0;
	@TarsStructProperty(order = 6, isRequire = false)
	public int iLvl = 0;
	@TarsStructProperty(order = 7, isRequire = false)
	public String sUrl = "";
	@TarsStructProperty(order = 8, isRequire = false)
	public boolean bCreateRole = false;

	public int getIZoneID() {
		return iZoneID;
	}

	public void setIZoneID(int iZoneID) {
		this.iZoneID = iZoneID;
	}

	public String getSName() {
		return sName;
	}

	public void setSName(String sName) {
		this.sName = sName;
	}

	public int getISvrStatue() {
		return iSvrStatue;
	}

	public void setISvrStatue(int iSvrStatue) {
		this.iSvrStatue = iSvrStatue;
	}

	public boolean getBExistRole() {
		return bExistRole;
	}

	public void setBExistRole(boolean bExistRole) {
		this.bExistRole = bExistRole;
	}

	public long getLLastTM() {
		return lLastTM;
	}

	public void setLLastTM(long lLastTM) {
		this.lLastTM = lLastTM;
	}

	public short getNRoleStatus() {
		return nRoleStatus;
	}

	public void setNRoleStatus(short nRoleStatus) {
		this.nRoleStatus = nRoleStatus;
	}

	public int getILvl() {
		return iLvl;
	}

	public void setILvl(int iLvl) {
		this.iLvl = iLvl;
	}

	public String getSUrl() {
		return sUrl;
	}

	public void setSUrl(String sUrl) {
		this.sUrl = sUrl;
	}

	public boolean getBCreateRole() {
		return bCreateRole;
	}

	public void setBCreateRole(boolean bCreateRole) {
		this.bCreateRole = bCreateRole;
	}

	public TUserZoneInfo() {
	}

	public TUserZoneInfo(int iZoneID, String sName, int iSvrStatue, boolean bExistRole, long lLastTM, short nRoleStatus, int iLvl, String sUrl, boolean bCreateRole) {
		this.iZoneID = iZoneID;
		this.sName = sName;
		this.iSvrStatue = iSvrStatue;
		this.bExistRole = bExistRole;
		this.lLastTM = lLastTM;
		this.nRoleStatus = nRoleStatus;
		this.iLvl = iLvl;
		this.sUrl = sUrl;
		this.bCreateRole = bCreateRole;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(iZoneID);
		result = prime * result + TarsUtil.hashCode(sName);
		result = prime * result + TarsUtil.hashCode(iSvrStatue);
		result = prime * result + TarsUtil.hashCode(bExistRole);
		result = prime * result + TarsUtil.hashCode(lLastTM);
		result = prime * result + TarsUtil.hashCode(nRoleStatus);
		result = prime * result + TarsUtil.hashCode(iLvl);
		result = prime * result + TarsUtil.hashCode(sUrl);
		result = prime * result + TarsUtil.hashCode(bCreateRole);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TUserZoneInfo)) {
			return false;
		}
		TUserZoneInfo other = (TUserZoneInfo) obj;
		return (
			TarsUtil.equals(iZoneID, other.iZoneID) &&
			TarsUtil.equals(sName, other.sName) &&
			TarsUtil.equals(iSvrStatue, other.iSvrStatue) &&
			TarsUtil.equals(bExistRole, other.bExistRole) &&
			TarsUtil.equals(lLastTM, other.lLastTM) &&
			TarsUtil.equals(nRoleStatus, other.nRoleStatus) &&
			TarsUtil.equals(iLvl, other.iLvl) &&
			TarsUtil.equals(sUrl, other.sUrl) &&
			TarsUtil.equals(bCreateRole, other.bCreateRole) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(iZoneID, 0);
		if (null != sName) {
			_os.write(sName, 1);
		}
		_os.write(iSvrStatue, 2);
		_os.write(bExistRole, 3);
		_os.write(lLastTM, 4);
		_os.write(nRoleStatus, 5);
		_os.write(iLvl, 6);
		if (null != sUrl) {
			_os.write(sUrl, 7);
		}
		_os.write(bCreateRole, 8);
	}


	public void readFrom(TarsInputStream _is) {
		this.iZoneID = _is.read(iZoneID, 0, false);
		this.sName = _is.readString(1, false);
		this.iSvrStatue = _is.read(iSvrStatue, 2, false);
		this.bExistRole = _is.read(bExistRole, 3, false);
		this.lLastTM = _is.read(lLastTM, 4, false);
		this.nRoleStatus = _is.read(nRoleStatus, 5, false);
		this.iLvl = _is.read(iLvl, 6, false);
		this.sUrl = _is.readString(7, false);
		this.bCreateRole = _is.read(bCreateRole, 8, false);
	}

}
