// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.yoooum;

public interface YOOOUMConst {
	/************************************************************************************/
	public static final int MATCH_CHANGE_TYPE_ADD = 1;

	public static final int MATCH_CHANGE_TYPE_DEL = 2;

	public static final int MATCH_CHANGE_TYPE_MODIFY = 3;

	public static final int MAX_MATCH_PVP_MEM_NUM = 4;

	public static final int MAX_NICKNAME_LEN = 20;

	public static final int MAX_HEAD_URL_LEN = 20;

	public static final int MAX_RECENT_CANCEL_ROOMID_NUM = 3;

	public static final int MAX_POP_ITEM_NUMBER = 24;

	public static final int MAX_PVP_MEM_STAT_NUM = 15;

	public static final int MAX_PVP_MEM_NUM = 4;

	public static final int FAVOR_ITEM_ID_1 = 302;

	public static final int FAVOR_ITEM_ID_2 = 303;

	public static final int FAVOR_ITEM_ID_3 = 304;

	public static final int FAVOR_ITEM_ID_4 = 305;

	public static final int FAVOR_ITEM_ID_5 = 306;
}
