// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.commdata;

public interface CommDataConst {

	public static final int DB_BAG_RESOURCE_MAX = 200;

	public static final int DB_MAX_BASE_INFO_COUNT = 50;

	public static final int RES_DEFAULT_MAX_STACK = 9999;

	public static final int RES_EXCEED_MAX_STACK = 150000;

	public static final int DEFAULT_MAX_LVL_DIFF = 1;

	public static final int ROLE_EQUID_GRID_COUNT = 6;

	public static final int ROLE_DEFAULT_MAX_COUNT = 16;

	public static final long RES_DEFAULT_MAX_TIME = 2682259200L;

	public static final int GLOBAL_BASE_RATIO = 10000;

	public static final int RES_BAG_MAX_STACK = 99;

	public static final int RES_BAG_MAX_SHORTCUT = 6;

	public static final int DEFAULT_FARM_NUM = 0;

	public static final int MAX_FARM_NUM = 24;

	public static final int MAX_NEWBIE_TYPE = 15;

	public static final int MAX_PASTURE_ANIMAL_NUM = 30;

	public static final int ITEMUSETYPE_MASK_NULL = 0;

	public static final int ITEMUSETYPE_MASK_AUTOOPEN = 1;

	public static final int ITEMUSETYPE_MASK_USEROPEN = 2;

	public static final short SEND_ITEM_TYPE_DIRECT = 1;

	public static final short SEND_ITEM_TYPE_SINGLERAND = 2;

	public static final short SEND_ITEM_TYPE_COMBRAND = 3;
}
