// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.commdata;

public enum E_CONDITION_TYPE {

	E_CONDITION_TYPE_GF(0),
	E_CONDITION_TYPE_WQ(1),
	E_CONDITION_TYPE_CF(2),
	E_ITEM_USE_TYPE_2002(2002),
	E_ITEM_USE_TYPE_2004(2004),
	E_ITEM_USE_TYPE_2006(2006);

	private final int value;

	private E_CONDITION_TYPE(int value) {
		this.value = value;
	}

	public int value() {
		return this.value;
	}

	@Override
	public String toString() {
		return this.name() + ":" + this.value;
	}

	public static E_CONDITION_TYPE convert(int value) {
		for(E_CONDITION_TYPE v : values()) {
			if(v.value() == value) {
				return v;
			}
		}
		return null;
	}
}
