// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.commdata;

public enum E_DCACHE_MODULE {

	E_DCACHE_MODULE_ACCOUNT(1);

	private final int value;

	private E_DCACHE_MODULE(int value) {
		this.value = value;
	}

	public int value() {
		return this.value;
	}

	@Override
	public String toString() {
		return this.name() + ":" + this.value;
	}

	public static E_DCACHE_MODULE convert(int value) {
		for(E_DCACHE_MODULE v : values()) {
			if(v.value() == value) {
				return v;
			}
		}
		return null;
	}
}
