// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.commdata;

public enum E_ITEM_USE_TYPE {

	E_ITEM_USE_TYPE_NONE(0),
	E_ITEM_USE_TYPE_CHOP(1),
	E_ITEM_USE_TYPE_MINING(2),
	E_ITEM_USE_TYPE_SEED(4),
	E_ITEM_USE_TYPE_HF(5);

	private final int value;

	private E_ITEM_USE_TYPE(int value) {
		this.value = value;
	}

	public int value() {
		return this.value;
	}

	@Override
	public String toString() {
		return this.name() + ":" + this.value;
	}

	public static E_ITEM_USE_TYPE convert(int value) {
		for(E_ITEM_USE_TYPE v : values()) {
			if(v.value() == value) {
				return v;
			}
		}
		return null;
	}
}
