// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.commdata;

public enum E_ITEM_ID_REGION {

	ID_ITEM_BASE_MAX(200),
	ID_ITEM_COMMON_MIN(201),
	ID_ITEM_COMMON_MAX(40000),
	ID_ITEM_PACKAGE_MIN(40001),
	ID_ITEM_PACKAGE_MAX(60000),
	ID_ITEM_TIMED_MIN(60001),
	ID_ITEM_TIMED_MAX(80000),
	ID_ITEM_EQUIPMENT_MIN(100000),
	ID_ITEM_EQUIPMENT_MAX(2000000);

	private final int value;

	private E_ITEM_ID_REGION(int value) {
		this.value = value;
	}

	public int value() {
		return this.value;
	}

	@Override
	public String toString() {
		return this.name() + ":" + this.value;
	}

	public static E_ITEM_ID_REGION convert(int value) {
		for(E_ITEM_ID_REGION v : values()) {
			if(v.value() == value) {
				return v;
			}
		}
		return null;
	}
}
