// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.commdata;

public enum E_MAIL_STATUS {

	E_MAIL_STATUS_NORMAL(0),
	E_MAIL_STATUS_READ(1),
	E_MAIL_STATUS_AWARD(2),
	E_MAIL_STATUS_DEL(3);

	private final int value;

	private E_MAIL_STATUS(int value) {
		this.value = value;
	}

	public int value() {
		return this.value;
	}

	@Override
	public String toString() {
		return this.name() + ":" + this.value;
	}

	public static E_MAIL_STATUS convert(int value) {
		for(E_MAIL_STATUS v : values()) {
			if(v.value() == value) {
				return v;
			}
		}
		return null;
	}
}
