// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.commdata;

public enum E_SOURCE_TYPE {

	E_SOURCE_COMM(0),
	E_SOURCE_UPGRADE_EQUIPMENT(1),
	E_SOURCE_EVALUATION_EQUIPMENT(2),
	E_SOURCE_SALE_EQUIPMENT(3),
	E_SOURCE_BUY_ITEM(4),
	E_SOURCE_OPEN_BOX(5),
	E_SOURCE_BATTLE(6),
	E_SOURCE_UPGRADE(7),
	E_SOURCE_REVIVE(8),
	E_SOURCE_ADD_VIT_BY_AD(9),
	E_SOURCE_ADD_VIT_OTHER_DAY(10),
	E_SOURCE_START_BATTLE(11),
	E_SOURCE_EVENT(12),
	E_SOURCE_GAME_OVER_CLEARING(13),
	E_SOURCE_AD_DRAW(14),
	E_SOURCE_GET_MAIL_ACCESSORY(15),
	E_SOURCE_CHARGE(16),
	E_SOURCE_EXCHANGE(17),
	E_SOURCE_SYSTEM_INI(18),
	E_SOURCE_SIGN_ACT(19),
	E_SOURCE_UPGRADE_ROLE(20),
	E_SOURCE_STORE_UP(21),
	E_SOURCE_STORE_DEL(22),
	E_SOURCE_EXTRACT_ITEM(23),
	E_SOURCE_FARMING(24),
	E_SOURCE_FARM_UNLOCK(25),
	E_SOURCE_FARM_GET(26),
	E_SOURCE_FARM_SHIFEI(27),
	E_SOURCE_ACTIVATE_ACHI(28),
	E_SOURCE_HONOR_REWARD(29),
	E_SOURCE_CHANGE_ITEM_NUM(30),
	E_SOURCE_UNLOCK_ROLE(31),
	E_SOURCE_UP_WORKSHOP(32),
	E_SOURCE_WORKSHOP_MERGER(33),
	E_SOURCE_PASTURE_GRAZE(34),
	E_SOURCE_ADD_FODDER(35),
	E_SOURCE_PASTURE_UP(36),
	E_SOURCE_PASTURE_FEED(37),
	E_SOURCE_PASTURE_REAP(38),
	E_SOURCE_PASTURE_PICKUP_SHIT(39),
	E_SOURCE_ACCEPT_TASK(40),
	E_SOURCE_TASK_AWARD(41),
	E_SOURCE_SUB_TASK_COST(42),
	E_SOURCE_USE_ITEM(43),
	E_SOURCE_NPC_AWARD(44),
	E_SOURCE_DISPATCH_TOUR(45),
	E_SOURCE_HHZ_STORE_REFRESH(46),
	E_SOURCE_ANIMAL_EVENT(47),
	E_SOURCE_ITEM_WEAR_UP(48),
	E_SOURCE_GM(1000);

	private final int value;

	private E_SOURCE_TYPE(int value) {
		this.value = value;
	}

	public int value() {
		return this.value;
	}

	@Override
	public String toString() {
		return this.name() + ":" + this.value;
	}

	public static E_SOURCE_TYPE convert(int value) {
		for(E_SOURCE_TYPE v : values()) {
			if(v.value() == value) {
				return v;
			}
		}
		return null;
	}
}
