// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.commdata;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TBuffMsg {

	@TarsStructProperty(order = 0, isRequire = false)
	public int iMsgId = 0;
	@TarsStructProperty(order = 1, isRequire = false)
	public int iMsgType = 0;
	@TarsStructProperty(order = 2, isRequire = false)
	public String sMsg = "";

	public int getIMsgId() {
		return iMsgId;
	}

	public void setIMsgId(int iMsgId) {
		this.iMsgId = iMsgId;
	}

	public int getIMsgType() {
		return iMsgType;
	}

	public void setIMsgType(int iMsgType) {
		this.iMsgType = iMsgType;
	}

	public String getSMsg() {
		return sMsg;
	}

	public void setSMsg(String sMsg) {
		this.sMsg = sMsg;
	}

	public TBuffMsg() {
	}

	public TBuffMsg(int iMsgId, int iMsgType, String sMsg) {
		this.iMsgId = iMsgId;
		this.iMsgType = iMsgType;
		this.sMsg = sMsg;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(iMsgId);
		result = prime * result + TarsUtil.hashCode(iMsgType);
		result = prime * result + TarsUtil.hashCode(sMsg);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TBuffMsg)) {
			return false;
		}
		TBuffMsg other = (TBuffMsg) obj;
		return (
			TarsUtil.equals(iMsgId, other.iMsgId) &&
			TarsUtil.equals(iMsgType, other.iMsgType) &&
			TarsUtil.equals(sMsg, other.sMsg) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(iMsgId, 0);
		_os.write(iMsgType, 1);
		if (null != sMsg) {
			_os.write(sMsg, 2);
		}
	}


	public void readFrom(TarsInputStream _is) {
		this.iMsgId = _is.read(iMsgId, 0, false);
		this.iMsgType = _is.read(iMsgType, 1, false);
		this.sMsg = _is.readString(2, false);
	}

}
